### ISSUE TITLE
struct for PullRequest under PullRequestEvent does not have "_links"

### ISSUE THREAD

**Issue by aashakabra** [google/go-github#1001]
Hi,

When my webhook is configured for Pull Requests event, the delivered payload has "_links" within "pull_request" object whereas I don't see it defined under https://godoc.org/github.com/google/go-github/github#PullRequest struct.

Can you please confirm if this sdk is compatible with v3 version of github APIs?

**Comment by gmlewis** [comment]
Yes, this package supports v3 of the GitHub API.

I see from https://developer.github.com/v3/activity/events/types/#pullrequestevent
that it does provide "_links" but we currently don't list them in our struct as you pointed out. Fortunately, all those links are trivial to recreate since they follow a common pattern.

If you feel those would be beneficial to provide in our struct, you (or anyone) are welcome to submit a Pull Request.

Thanks.

**Comment by radlinskii** [comment]
Hi, I would love to be assigned to do this one. :)

**Comment by gmlewis** [comment]
I can't invite you to be a contributor, but consider yourself assigned.
😁
