### ISSUE TITLE
Support new Webhook Event for Repository Vulnerability Alerts

### ISSUE THREAD

**Issue by thepwagner** [google/go-github#1005]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-04-24-preview-dependency-graph-and-vulnerability-hooks/

**Comment by gmlewis** [comment]
Thank you, @thepwagner!
I remember reading that and thinking that this was a GraphQL (v4) -only change, but from your original link: https://developer.github.com/changes/3/#repository-vulnerability-alerts-webhooks
it is more clear that it also affects v3 (and therefore, this repo).

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by gmlewis** [comment]
Welcome to Go, @akhilerm and thank you for helping this project!

**Comment by gmlewis** [comment]
As requested off-line, here is some information that should be helpful to new Go developers who would like to contribute to this repo.

First off, I highly recommend reading our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide. The section called ["Other notes on code organization"](https://github.com/google/go-github/blob/master/CONTRIBUTING.md#other-notes-on-code-organization) explains this repo's philosophy on code organization and should get you up-to-speed quickly. All structs are named as closely to their GitHib API Documentation counterparts as possible.

Another helpful resource to understand the "big picture" for this repo is our auto-generated (from the code) godocs link:
https://godoc.org/github.com/google/go-github/github

If you think that any of these resources are lacking in any way, then you are welcome to submit PRs that you believe will improve them. Once the PRs are created, then all contributors of this repo will have an opportunity to discuss the suggested improvements as a community.

Good luck! Let me know if I can help further.

**Comment by akhilerm** [comment]
Based on my understading, is this the path that I should follow.

1. Include an `eventTypeMapping` in `messages.go` for  `repository_vulnerability_alert`
2.Create a `RepositoryVulnerabilityAlertEvent` type in `event_types.go`
3. Assign the event payload in `activity_events.go`

Is this the correct way?

**Comment by gmlewis** [comment]
Yes, that sounds like a good plan to me.

**Comment by gmlewis** [comment]
Fixed by #1025.
