### ISSUE TITLE
Add two_factor_authentication to User data

### ISSUE THREAD

**Issue by josebarn** [google/go-github#1053]
The github API v3 for GET user supplies an indicator for two_factor_authentication, however is it not available in the User object. Is there a reason is not added? Can this be added?

See `two_factor_authentication` in the reference:
https://developer.github.com/v3/users/#response-with-public-and-private-profile-information

**Comment by gmlewis** [comment]
Excellent point, @josebarn!  This field should be added to the `User` struct in `users.go`.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by srmocher** [comment]
@gmlewis I'm happy to take up this issue.

**Comment by shakeelrao** [comment]
Ah, didn't see the previous comment prior to working on the PR.

My bad!

**Comment by gmlewis** [comment]
Yes, sorry about the snafu, @srmocher. There are more issues to address... thank you for your understanding on this mixup.
