### ISSUE TITLE
ProjectCard is not supported for issue timeline

### ISSUE THREAD

**Issue by smola** [google/go-github#1091]
Project card fields from the starfox preview was added for IssueEvent (https://github.com/google/go-github/pull/1066/files). It's still not present for issue timeline though.

See https://developer.github.com/v3/issues/timeline/#list-events-for-an-issue

**Comment by gmlewis** [comment]
Thank you, @smola!

To resolve this, a similar change to #1066 would need to be made to `issues_timeline.go`.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by rleungx** [comment]
May I take this one?

**Comment by gmlewis** [comment]
Thank you, @rleungx! It's yours.
I'm unable to send an invite, but consider it yours.
