### ISSUE TITLE
Incorrect endpoints for adding and removing repositories for app installations

### ISSUE THREAD

**Issue by ardakuyumcu** [google/go-github#1095]
The endpoints requested in the below functions are incorrect, and are missing the preview headers:
```
func (s *AppsService) AddRepository(ctx context.Context, instID, repoID int64) (*Repository, *Response, error) {
	u := fmt.Sprintf("apps/installations/%v/repositories/%v", instID, repoID)
```
```
func (s *AppsService) RemoveRepository(ctx context.Context, instID, repoID int64) (*Response, error) {
	u := fmt.Sprintf("apps/installations/%v/repositories/%v", instID, repoID)
```

The API endpoints are `user/installations/...` and not `apps/installations/...`

Planning to submit a fix for the issue.

**Comment by gmlewis** [comment]
Good catch, @ardakuyumcu! I'm not sure how that happened.

For others taking a look, this issue is talking about:
https://developer.github.com/v3/apps/installations/#add-repository-to-installation
https://developer.github.com/v3/apps/installations/#remove-repository-from-installation

and lines 75 and 94 of `github/apps_installation.go`.

**Comment by ardakuyumcu** [comment]
Submitted https://github.com/google/go-github/pull/1096 as the fix
