### ISSUE TITLE
Missing integration tests for repository releases

### ISSUE THREAD

**Issue by aidenkeating** [google/go-github#1105]
This is covered more broadly in some other issues on the repo. There are currently no integration tests for releases. It would be great to be able to test this release functionality against the GitHub API itself.

Basically, creating integration tests to cover the functionality provided from https://github.com/google/go-github/blob/master/github/repos_releases.go

I'm happy to take this on if it seems like a worthwhile effort.

**Comment by gmlewis** [comment]
Historically, we have found integration tests to be challenging due to the need to have a dedicated GitHub repo to test this against. 

Note that we do have this: https://github.com/google/go-github/tree/master/test/integration
but we (at least I) have not regularly run these tests and we certainly don't have TravisCI hit the GitHub API. Travis does check that the integration tests build successfully, but that is it at this point.

One other thing is that we don't want to hit the GitHub API regularly for test purposes in order to honor their terms of service.

**Comment by aidenkeating** [comment]
Ah I wasn't aware that Travis does not hit the GitHub API already, and the reasons why make sense. Thanks for the detailed explanation! I'm happy to close this.
