### ISSUE TITLE
Remove deprecated API endpoints by April 1, 2019

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1109]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-01-29-life-after-github-services/

These deprecated API endpoints need to be removed, preferably by April 1, 2019.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by joshuabezaleel** [comment]
Hi @gmlewis , if it is okay with you I would like to ask some questions.

Since the [announcement](https://developer.github.com/changes/2019-01-29-life-after-github-services/) told us that there will be 3 endpoints affected which I found [here](https://github.com/google/go-github/blob/master/github/repos_hooks.go), does this mean that we are going to replace it by using GitHub Apps?

**Comment by gmlewis** [comment]
Yes, that is my understanding from the announcement. Others may have more insights.

**Comment by joshuabezaleel** [comment]
For this specific issue, do we need to only remove the codes that use the 3 service hooks endpoints, or including making the GitHub Apps for the hooks?

**Comment by gmlewis** [comment]
For this specific issue, only the deprecated endpoints need to be removed.

We have a number of other open (and closed) issues for GitHub Apps webhooks:
https://github.com/google/go-github/issues?utf8=%E2%9C%93&q=is%3Aissue+%22GitHub+Apps%22
