### ISSUE TITLE
GHE replication status

### ISSUE THREAD

**Issue by s4mur4i** [google/go-github#1146]
Hello,

I would be interested to know if there is an api endpoint to get information about GHE replication status like from cli tool: ghe-repl-status
https://help.github.com/en/enterprise/2.15/admin/installation/about-high-availability-configuration
In developer documentation I didn't find any reference or information to such objects.

Thank you

**Comment by gmlewis** [comment]
I highly recommend that you click on the "Contact Us" button located on that same page:

![image](https://user-images.githubusercontent.com/6598971/55553525-6f1d4c00-56ae-11e9-883c-99fc4f556a65.png)

and ask them.

The maintainers of this repo have very little exposure to GitHub Enterprise and work solely off of the GitHub Developer API v3 documentation.

As I mentioned in another issue, the GitHub Tech Support team is an exceptionally helpful, friendly, and knowledgeable team and should be able to answer your questions quickly and accurately.

Best wishes to you. Feel free to report back the answer you get in this (closed) issue so that other GHE users might benefit (by searching).
