### ISSUE TITLE
List all Commits for a given PullRequest

### ISSUE THREAD

**Issue by dmigo** [google/go-github#1148]
It would be handy to have a possibility to list all commits for a given `PullRequest`.

I would start a PR with implementation, but I'm not sure where is the best place for such a function in the project.

**Comment by gmlewis** [comment]
Typically we have asked that developers place utility functions like this in their own repos so that we are not increasing the surface area of an already very large API, and also to keep maintenance costs lower on this repo.

However, if the community thinks this is a great idea, and we have some strong support for adding it, then I will not stand in the way. Let's see what others think and then we can discuss where to put it.

**Comment by wesleimp** [comment]
@gmlewis Can I take this issue over or can we close it?

**Comment by gmlewis** [comment]
Seeing that there was no strong support for adding this feature, I'm closing the issue.
