### ISSUE TITLE
Add method for updating a pull request review

### ISSUE THREAD

**Issue by SudoVim** [google/go-github#1174]
It looks like this project is missing a method for updating an existing review: https://developer.github.com/v3/pulls/reviews/#update-a-pull-request-review. All of the other methods seem to be implemented, but I need this one in particular.

**Comment by gmlewis** [comment]
Ah, yes... thank you for pointing this out, @SudoVim!

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by SudoVim** [comment]
Well, it looks as if someone beat me to it. At any rate, this feature is greatly appreciated!
