### ISSUE TITLE
Certains fields do not display when calling ListCommits

### ISSUE THREAD

**Issue by anjanashenoy** [google/go-github#1210]
I'm using go-github for an internal tool on Github enterprise. There are certain fields that do not show up when I call the github commits API using go-github, but when I call the github API directly these fields are visible. Is there anyway to get the commit data using go-github before the data is Unmarshaled into a struct?

**Comment by gmlewis** [comment]
Yes, by modifying the `go-github` source code and adding in the missing fields (if it is urgent).
If it is not urgent, then you can list all the missing fields in this Issue #1210 and one of our gracious and awesome volunteer contributors will be happy to add the fields for you. Or, you could create a PR and become a contributor to this repo yourself, which you are welcome to do! Your choice.

**Comment by anjanashenoy** [comment]
Thank you! I need this field added for a User/Author:

`LdapDn            			string 		 `json:"ldap_dn"``

**Comment by gmlewis** [comment]
Sounds great, @anjanashenoy !

Dear contributors:

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by anjanashenoy** [comment]
Please review https://github.com/google/go-github/pull/1211

**Comment by gmlewis** [comment]
It looks like it is not quite ready yet... it probably just needs a `gofmt` on your changed file that you edited.
