### ISSUE TITLE
Invalid response expected for ListPlanAccountsForAccount

### ISSUE THREAD

**Issue by domsu** [google/go-github#1270]
Currently `ListPlanAccountsForAccount` from `MarketplaceService` expects `[]*MarketplacePlanAccount`.

But documentation https://developer.github.com/v3/apps/marketplace/#check-if-a-github-account-is-associated-with-any-marketplace-listing says that `GET /marketplace_listing/accounts/:account_id` returns `*MarketplacePlanAccount`.

This is causing my application to fail.

**Comment by gmlewis** [comment]
Closing issue as obsolete.

If anyone is still having this issue with the latest version of the repo, please first contact support@github.com to clarify the documentation as mentioned in #1271 and then reopen this issue and we can proceed with a fix.

**Comment by JarmoDi2** [comment]
Hi @gmlewis, would it be possible to reopen this issue or merge the PR?

GitHub seem to have updated their docs and there's no more paging support for this endpoint:
https://docs.github.com/en/rest/reference/apps#get-a-subscription-plan-for-an-account

I'm also experiencing the same error with go-github v33.

**Comment by gmlewis** [comment]
Thank you @JarmoDi2 .

Specifically, this method: https://github.com/google/go-github/blob/master/github/apps_marketplace.go#L129-L132
needs to have the `opts *ListOptions` parameter removed and the `GitHub API Docs:` URL updated.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by sethaustinx** [comment]
@gmlewis hi, I'd like to volunteer for this issue. I've made a PR.

**Comment by gmlewis** [comment]
I'm now a little bit confused... I thought that @JarmoDi2 had requested this issue to be re-opened and wrote some detailed information as to why... I can only assume that the user deleted the comment, and the details with it, which is unfortunate.
