### ISSUE TITLE
Add support for allowing apps to push to protected branches

### ISSUE THREAD

**Issue by mungojam** [google/go-github#1275]
Support has just been added to the REST API:

https://developer.github.com/changes/2019-09-05-apps-protected-branches-api/

The main benefit for us will be to give dependabot permissions to auto-merge protected branches.

**Comment by gmlewis** [comment]
Thank you, @mungojam!

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by shibasisp** [comment]
@gmlewis I am a new contributor to this repo as well as a new Go developer. Can I pick this issue?

**Comment by gmlewis** [comment]
Hi @shibasisp, yes, you are welcome to take this issue, and thank you for volunteering!

Note that the successful closing of this issue will involve creating four new methods and enhancing one existing one. Please make sure to compliment each new method with unit tests and carefully follow the instructions found in [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md).

Feel free to ask questions either in this issue or in your PR. Also, there's no rush on the PR... please take your time and try to get everything working to your satisfaction first.

Thanks again!
