### ISSUE TITLE
Add search topics

### ISSUE THREAD

**Issue by lucmski** [google/go-github#1284]
Hi guys,

Hope you are all well !

It would be awesome to add search topics.
https://developer.github.com/v3/search/#search-topics
https://github.com/google/go-github/blob/master/github/search.go

Cheers,
L.

**Comment by gmlewis** [comment]
Thank you, @lucmski!

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by AGMETEOR** [comment]
@gmlewis I am quite new to the language, about 6 months in... I am curious if a person with my little experience would handle this ticket? Although something in me tells I can do it but will struggle a bit.

**Comment by gmlewis** [comment]
Welcome, @AGMETEOR! I would definitely have said yes, but it looks like @lucmski is already working on this one in #1285.

Feel free to pick out any other issues in this repo to work on, especially those flagged as `good first issue` and I'm happy to help you through the process.
