### ISSUE TITLE
Support multi-line comments with custom media header

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1297]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-10-03-multi-line-comments/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by waseem18** [comment]
@gmlewis I'd like to pick this up

**Comment by gmlewis** [comment]
It's yours, @waseem18.  Thank you!

**Comment by davidlopezre** [comment]
Hi @gmlewis,

We worked on this issue as part of a Hacktoberfest event (PR #1326). We had a chat with a few open source contributors and thought it was okay to work on it as there was no visible progress for it and it was assigned for a while.

Hi @waseem18 wanted to ask if you are still actively working on this. We would like to work on it otherwise. All good regardless :)

Cheers!

**Comment by waseem18** [comment]
Somehow I lost track of this issue and I see that you've already drafted a PR for this.

I think you go ahead working on this issue :)

Thanks

**Comment by gmlewis** [comment]
OK, thanks, @waseem18 - I'll reopen PR #1326 and @davidlopezre can continue.
