### ISSUE TITLE
Rate Limit handling may not work with GitHub Enterprise

### ISSUE THREAD

**Issue by tkhandel** [google/go-github#1318]
In the code at [github/github.go#L766](https://github.com/google/go-github/blob/master/github/github.go#L766), it parses the response body to check if the message starts with the words "API rate limit exceeded for ". 

Besides being brittle, it is also plain wrong for an enterprise version of GitHub. Reason - The error message which is returned seems to be a configurable option where an enterprise admin can tweak the exact message that is returned. I know this because at my company, the error message which is returned is different than this. Hence, the library is not able to correctly identify that the GitHub's rate limit has been reached. 

To rectify, remove the response body check. The HTTP status code and the corresponding rate-limiting headers ("X-RateLimit-Limit", "X-RateLimit-Remaining", "X-RateLimit-Reset") should be enough to confirm that it is indeed a rate-limiting error.

**Comment by gmlewis** [comment]
Thanks, @tkhandel.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Please make sure that your unit tests are comprehensive for this change.

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by xitter** [comment]
@gmlewis can I work on this?

**Comment by tkhandel** [comment]
@gmlewis Can you assign it to me?

**Comment by gmlewis** [comment]
Thank you, @xitter, but let's let @tkhandel work on this since @tkhandel is the issue reporter.

This is actually my fault for opening it up to everyone before asking if the issue author wanted to work on it, so I apologize. Thanks for your understanding.

@tkhandel - it is yours.  Thanks.

**Comment by tkhandel** [comment]
Thank you, @gmlewis. I will put up the PR soon.
