### ISSUE TITLE
 AddCollaborator - Invitation Id

### ISSUE THREAD

**Issue by safwanolaimat** [google/go-github#1329]
Hello
I think AddCollaborator function should return invitation Id

**Comment by gmlewis** [comment]
Looking at: https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator
I totally agree.  In fact, an entire response struct should be returned like the other methods (in addition to the original response and error values).

Here is the method we are talking about:
https://github.com/google/go-github/blob/master/github/repos_collaborators.go#L112-L124

Thank you, @safwanolaimat, for reporting this.  First, are you interested in writing a PR for this?

If not, this would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by rbrishabh** [comment]
Hey! Can I take this up?
Thanks!

**Comment by gmlewis** [comment]
Let's give @safwanolaimat a day to respond, please, @rbrishabh - if we don't hear from @safwanolaimat by tomorrow, we can safely say that you own the issue.  Thanks.

**Comment by safwanolaimat** [comment]
@gmlewis Sorry for late response because we have weekend here
i want to see how to contribute :]

**Comment by safwanolaimat** [comment]
@gmlewis can you assigned the pull request for me ?
I did one here https://github.com/google/go-github/pull/1330 but its failed

**Comment by gmlewis** [comment]
Thank you, @safwanolaimat - this issue is yours.  I'll take a look at #1330.
