### ISSUE TITLE
IssueListCommentsOptions is not consistent with GitHub API

### ISSUE THREAD

**Issue by tfujiwar** [google/go-github#1339]
## Problem
In the GitHub API document, an endpoint "list-comments-on-an-issue" takes only one parameter `since`.
https://developer.github.com/v3/issues/comments/#list-comments-on-an-issue

But `IssueListCommentsOptions` in this library takes 3 parameters `sort`, `direction` and `since`.
https://godoc.org/github.com/google/go-github/github#IssueListCommentsOptions

## Goal
Remove `sort` and `direction` from `IssueListCommentsOptions`.

**Comment by gmlewis** [comment]
No, this is not entirely correct.  This endpoint also serves this call:
https://developer.github.com/v3/issues/comments/#list-comments-in-a-repository

So when listing comments on an issue, the user should not populate `sort` or `direction`.

However, I see that there is indeed a bug. The `omitempty` is basically not useful as written because the two `string` options and the `time.Time` option should all be pointers.

The correct fix here is to make those three options pointers.

**Comment by tfujiwar** [comment]
I missed the case of an issue number of 0. Thank you.
