### ISSUE TITLE
Feature Request > New branch protection features support

### ISSUE THREAD

**Issue by kuwas** [google/go-github#1345]
Hi,

Please add support for the new branch protection features:
* `required_linear_history`
* `allow_force_pushes`
* `allow_deletions`

See: https://developer.github.com/v3/repos/branches/#update-branch-protection

Thanks!

**Comment by anorek** [comment]
could i try to work on this? :smiley:

**Comment by gmlewis** [comment]
Hi @anorek - I haven't had a chance to verify this one yet, so that would be the first step. So yes, it is yours. Thank you! 😁

**Comment by gmlewis** [comment]
I'm sorry, @anorek - it looks like @pcantea already submitted a PR for this.

@pcantea - in the future, could you please note in the issue (here) that you would like to work on it before sending a PR?  It was already assigned to @anorek and if we communicate clearly, it can hopefully avoid developer frustration and prevent duplication of effort.

So @anorek - I hope you have not wasted too much time on this issue... but if you are OK with moving forward with @pcantea's PR in #1354, then that's how we'll proceed. I'll assume that so that we can hopefully keep moving forward and start reviewing the PR.

**Comment by anorek** [comment]
Of course Glenn! No worries at all!

Have a lovely Christmas and please enjoy the holidays!

**Comment by gmlewis** [comment]
Thank you for your understanding, @anorek!  Merry Christmas to you too!

**Comment by anorek** [comment]
@gmlewis hey glen, just want to say that you are a wonderful maintainer! while I am grateful that you are such a hard worker and continue to create a good open source environment, I can only wish that you would be able to take the day off and enjoy the holiday and best of the health for you! :heart:

**Comment by gmlewis** [comment]
Thank you, @anorek, for the kind words!  Best wishes to you too!
