### ISSUE TITLE
The Tree API does not allow for file deletion 

### ISSUE THREAD

**Issue by dandonovsc** [google/go-github#1371]
In order to delete a file via the  [Github REST API v3](https://developer.github.com/v3/git/trees/#create-a-tree) a file's sha need to be null as per the documentation

> The SHA1 checksum ID of the object in the tree. Also called tree.sha. If the value is null then the file will be deleted. 

The library's implementation defines the `sha` field as a pointer to a string with  that will be ignored when json serialized:

```
type TreeEntry struct {
	SHA     *string 'json:"sha,omitempty"'
         ................
}
```

When submitting a `POST` request to the `repos/%v/%v/git/trees` API with no sha and no content validation fails with response `422 Must supply tree.sha or tree.content []`

Please advise how a file should be deleted using the library

**Comment by gmlewis** [comment]
Thank you, @dandonovsc, for the report.

It seems to me that the correct fix for this would be to check if both `tree.content` and `tree.sha` are empty, then use a different internal struct where the `,omitempty` has been removed from the `SHA` field which will then pass the `null` along and thereby delete the file.

Instead of opening this up to our volunteers, I'll write up my thoughts in a PR since I recently did something similar in #1357.

**Comment by mesaglio** [comment]
Is this still working?
I'm trying to delete a file but the api returns 422
```golang
var entries []github.TreeEntry
for _, file := range filesToDeleted {
    entryData := github.TreeEntry{
        Path:      github.String(file.Path),
	Type:      github.String("blob"),
	Content:   nil,
	SHA:       nil,
	Mode:      github.String("100644"),
    }
    entries = append(entries, entryData)
}
...
tree, err := gh.getTree(ctx, ref, owner, repository, entries)
```

Error: 
```
Unable to create the tree based on the provided entries: \
POST https://api.github.com/repos/ORG/REPO/git/trees: \
  422 Must supply either tree.sha or tree.content. \
  Request will be rejected if both are present. []
```
