### ISSUE TITLE
DownloadReleaseAsset should follow the redirect and download the resource

### ISSUE THREAD

**Issue by andersjanmyr** [google/go-github#1378]
Hi,

I think the `DownloadReleaseAsset` method should follow the redirect by default and to make it optional to return the redirectURL.

I read the discussion in https://github.com/google/go-github/pull/312, and I understand that a new `http.Client` needs to be used, but I don't understand why the api had to change.

It seems to me that most users of this method don't care where the file comes from and they will all have to write similar logic to perform the download after the redirectURL is returned.

What do you think? I would be happy to contribute the code.

**Comment by gmlewis** [comment]
Hmmm... I think there was a good reason... ah, yes... I believe it was because our http.Client could not easily be duplicated.

When using this repo, clients can set up different http.Clients that have different features... timeouts, proxies, etc. There wasn't a clean way to duplicate the http.Client with identical features.

However, having said that, I know that we modified another endpoint recently to add the option to follow the redirect. Yes, here it is:

https://github.com/gmlewis/go-github/blob/master/github/repos_contents.go#L243

So if you would like to put together a PR that adds a `followRedirects bool` option, then I think that would be a nice enhancement, and yet it will not force it on everybody for the cases where a special http.Client must be used (and a general redirect might fail).
