### ISSUE TITLE
Not able to get private repo information

### ISSUE THREAD

**Issue by palash25** [google/go-github#1382]
Hi I am trying to fetch all the repos (including private ones) including their PRs and Reviews. I am authenticating using my personal access token that has SSO enabled for the organization whose repos I want to fetch. But for some reason it only works for public repos and I dont see any private repos in my results

Here is the code

```go
        ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: "my-token"},
	)
	tc := oauth2.NewClient(ctx, ts)

	client := github.NewClient(tc)

       prs, _, err := client.PullRequests.List(ctx, "org-name", "private-repo-name", nil)
	checkErr(err)

	for _, pr := range prs {
		fmt.Println(*pr.Title)
	}
```

I get an error saying `GET https://api.github.com/repos/org-name/private-repo-name/pulls: 404 Not Found []` if I try to fetch the PRs of a private repo from that org

If however, I try a public repo it works.

I am able to access these repos on github

Am I authenticating my client correctly?

**Comment by palash25** [comment]
cc @gmlewis

**Comment by gmlewis** [comment]
Your code above works fine on my private repo.

So I'm assuming that from your account (where you got your personal access token), you can see the private repo.
I'm also assuming that your personal access token has full `repo` rights, which are required to see private repos.

If either of those statements are not true, your code above will not work.

Good luck.

**Comment by gmlewis** [comment]
Here is a screenshot of the scopes that my personal access token has, hoping that will help you:

![github-access-token-scopes-Screenshot from 2020-01-17 06-25-09](https://user-images.githubusercontent.com/6598971/72609186-535bfd00-38f2-11ea-9c41-a66d28bd9955.png)

**Comment by gmlewis** [comment]
Also, this may be obvious, but in order to be thorough, I need to state that the private repo must have at least one PR in order to get more than an empty list in response to the API call. 😁

**Comment by palash25** [comment]
The private repo is actually under an organization not under my account. I did check all the boxes while creating the access token and then enabled SSO on that token for the org.

I am able to view the repo on GitHub and it does have PRs.

**Comment by gmlewis** [comment]
The next step to debug this is to call the v3 API directly using `curl`. 

If you get results we can then try to figure out what is different between this repo and the curl version.

If you don't get expected results, then there is some other problem unrelated to this repo. As a last resort, you can then contact support@github.com and ask for their assistance.

**Comment by palash25** [comment]
Tried a curl request got a 404 again

**Comment by gmlewis** [comment]
OK, thank you for reporting back, @palash25 (and for closing).
Good luck fixing the problem!
(I'm not sure if you are using an Enterprise version of GitHub, but sometimes we have seen some odd differences in the way they operate, presumably because of the settings the particular organization chose to set when running their instance... or simply due to the (older) version they are using.  That might be something you want to investigate.)

**Comment by VladSavitsky** [comment]
I have the same issue with private repo. Problem was a missing token in request header.

**Comment by pathcl** [comment]
@VladSavitsky do you have an example using go-github?

**Comment by VladSavitsky** [comment]
No, I don't use go-github. I'm using github API in my own scripts.

**Comment by almo8800** [comment]
Another way: 

You may have problems with getting private repos, because u use the wrong link like this 

wrong: https:/api.github.com/users/"USERNAME"/repos 
tight: https:/api.github.com/user/repo [do not change USER to your profile name], just add bear token to request

**Comment by AndonMitev** [comment]
hey @almo8800 i'm facing similar error, generated PAT token with full access and then trying to access:

`https://github.com/AndonMitev/tauri-updater-private-repo/releases/latest/download/latest.json`

which will download a file, unfortunately throws 404 all the time i tried many different headers like:

```
Accept: application/vnd.api+json,
X-GitHub-Api-Version: 2022-11-28
``` 

but none of them seems to work no matter in what combination, can confirm url is correct because if i switch visibility from private to public i'am able to read it, any ideas
