### ISSUE TITLE
Support GitHub Actions API

### ISSUE THREAD

**Issue by joshuabezaleel** [google/go-github#1399]
Announcement: https://developer.github.com/v3/actions/

**Comment by gmlewis** [comment]
Usually there is a blog announcement, and apparently there wasn't for this.  Thanks, @joshuabezaleel.

This would be a great PR for any new contributor to this repo or any Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by gmlewis** [comment]
Assigned to @martinssipenko.

**Comment by gmlewis** [comment]
In order to fully close this issue, we need PRs that will address all the following sections of the announcement:

- [ ] `actions_artifacts.go`
- [x] `actions_secrets.go` (#1402 - assigned to @martinsspenko)
- [ ] `actions_runners.go`
- [ ] `actions_workflows.go`
- [ ] `actions_workflow_jobs.go`
- [ ] `actions_workflow_runs.go`

Since this is a lot of work, let's open this up to multiple developers... please volunteer for one section in the list above, and piggy-back upon the excellent work that @martinsspenko has started in #1402. 

Thank you!

**Comment by joshuabezaleel** [comment]
Haven't got a chance to look at it but I want to take a shot. Perhaps the `actions_workflows` one.

**Comment by atorr** [comment]
May I contribute to the actions_artifacts section?

**Comment by joshuabezaleel** [comment]
Since my incoming PR will be dependent to @martinssipenko 's [PR](https://github.com/google/go-github/pull/1402) that contains `ActionsService` on `actions.go`, should I wait for that particular PR to be merged or I can raise a PR with `ActionsService` written in my code as if it's already merged? 

cc: @gmlewis

**Comment by martinssipenko** [comment]
@joshuabezaleel you can branch off of my branch.

**Comment by gmlewis** [comment]
Hey volunteers, I am super-pleased with the way this Issue is coming together... starting off with the excellent groundwork from @martinssipenko followed by another great PR from @joshuabezaleel!

Let's keep up this excellent progress going by having more people volunteer to complete the unchecked and unassigned items [above](https://github.com/google/go-github/issues/1399#issuecomment-579554516).

Please remember to check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started... and thank you in advance for your contributions!

**Comment by nightlark** [comment]
Interested in getting the `actions_runners` working.

**Comment by gmlewis** [comment]
> Interested in getting the actions_runners working.

@nightlark - does that mean you are volunteering to implement `action_runners.go` or you are just interested that _someone_ gets this working?
I would hate to assign this issue to you if it is just the latter.  :smile:

If it is the former, thank you very much, and I will put your name as its owner.

**Comment by joshuabezaleel** [comment]
I would love to work more on this if it's permissible and no one is taking it. But if we should distribute the contribution, that would be lovely to do so :slightly_smiling_face: cc: @gmlewis

**Comment by gmlewis** [comment]
Hi @joshuabezaleel - that's fantastic... thank you!

I think we give people ample opportunity to sign up for working on this repo, so feel free to volunteer for more endpoints (as we await LGTMs).  (I think we should probably give @nightlark another day to respond to my question... so feel free to pick a different one while we are waiting for a response. :smile:)

**Comment by nightlark** [comment]
@gmlewis I’ll take on implementing support for the runners api.

**Comment by gmlewis** [comment]
> @gmlewis I’ll take on implementing support for the runners api.

Thank you, @nightlark! I've assigned `actions_runners.go` to you [above](https://github.com/google/go-github/issues/1399#issuecomment-579554516).

**Comment by gmlewis** [comment]
Hi awesome volunteers, we still have [one task above](https://github.com/google/go-github/issues/1399#issuecomment-579554516) that needs an implementation.

Now that pioneers like @martinssipenko, @joshuabezaleel, and @atorr have forged ahead with their portions, there are excellent examples to base the remaining work upon.

Please remember to check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started... and thank you in advance for your contributions!

**Comment by ayzu** [comment]
Hi guys!

I would like to work on the last issue: actions_workflow_runs.go

**Comment by gmlewis** [comment]
Thank you, @ayzu!  It is yours.

**Comment by bramwelt** [comment]
Testing out the [CreateOrUpdateSecret](https://github.com/google/go-github/blob/master/github/actions_secrets.go#L109) function, I seem to always be getting a `204 No Content` response back even when creating new secrets (which should return `201 Created`). I'm curious if anyone else has seen this or if perhaps I'm getting a cached response from my own code?

**Comment by gmlewis** [comment]
@martinssipenko - can you please comment on https://github.com/google/go-github/issues/1399#issuecomment-592118436 ?

**Comment by martinssipenko** [comment]
@gmlewis @bramwelt I tested the API manually and despite what documentations suggests, it indeed returns `204 No Content` on both create and update.

I've reached out to GitHub support and updated the conversion with them  in #1402, https://github.com/google/go-github/pull/1402#issuecomment-592332173

**Comment by gmlewis** [comment]
Thank you, @martinssipenko !  Your efforts are greatly appreciated!

**Comment by joshuabezaleel** [comment]
Agreed, thank you lots @martinssipenko !! Truly appreciate it :slightly_smiling_face:
