### ISSUE TITLE
Update teams_members.go

### ISSUE THREAD

**Issue by adrienzieba** [google/go-github#1422]
Hello,

Related to https://github.com/google/go-github/issues/1387, I noticed that all teams endpoints are affected

- https://developer.github.com/v3/teams/members/
- https://developer.github.com/v3/teams/discussion_comments/
- https://developer.github.com/v3/teams/discussions/

Is it possible to update other teams files?

**Comment by gmlewis** [comment]
Thank you, @adrienzieba!

It seems that the [original blog post](https://developer.github.com/changes/2020-01-21-moving-the-team-api-endpoints/) that we were basing #1387 on didn't mention these changes.

Let's split this up into three issues to organize the work:

This issue will be for updating `teams_members.go`.

The work involved here it to update every endpoint listed here:
https://developer.github.com/v3/teams/members/
Note that #1400 can be used as a model because most endpoints have two ways to call them: `*ByID` and `*BySlug`. The same pattern should be followed for these updates.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by adrienzieba** [comment]
Hello,

I want to work on this one. Can you assign it to me please?

Thank you

**Comment by gmlewis** [comment]
Thank you, @adrienzieba!
It is yours.
