### ISSUE TITLE
Errors.Code == "custom" when from Client.PullRequests.Create when PR already exists

### ISSUE THREAD

**Issue by jwtracy** [google/go-github#1441]
Here is the ErrorsResponse.Error() output,

```
POST https://api.github.com/repos/***/***/pulls: 422 Validation Failed [{Resource:PullRequest Field: Code:custom Message:A pull request already exists for ***:***.}]
```

It would be convenient if `Code:already_exists` for `Resource:PullRequest` so I can use that rather than parsing the Message for "A pull request already exists"

Is it "custom" because the `<owner>:<branch>` string is not necessarily a unique key across Github? When creating a PR in a repository between two branches, this is a unique resource, however.

**Comment by gmlewis** [comment]
Hmmm... looking at the code, it appears to me that this code is generated by the GitHub v3 API endpoint:
https://developer.github.com/v3/#client-errors

You might want to contact support@github.com and point them to:
https://developer.github.com/v3/pulls/#create-a-pull-request
and describe the problem like you did above, that you would like an `already_exists` error to be returned instead of a `custom` error in the situation you described.

If you do contact them, please report back here what they say. They are usually very fast to reply and are always friendly and helpful.

Thank you!

**Comment by elemanhillary** [comment]
@gmlewis would you please assign this to me

**Comment by gmlewis** [comment]
@elemanhillary - does that mean you want to contact GitHub tech support?  There is nothing yet here to work on. Let's see if @jwtracy responds about contacting GitHub tech support first before I assign this ticket to anyone.  Thanks.

**Comment by gmlewis** [comment]
Closing inactive issue for lack of activity/interest.  Feel free to reopen.
