### ISSUE TITLE
Return app "slug" in AppService.Get?

### ISSUE THREAD

**Issue by lollipopman** [google/go-github#1463]
`Client.Apps.Get(ctx, "")` returns the authenticated app, but does not return the "slug" name of the app in the `App` struct, is it possible to include the slug, as it appears to be in the response?, https://developer.github.com/v3/apps/#get-the-authenticated-github-app, thanks!

**Comment by gmlewis** [comment]
You should indeed already be getting the `slug` name in the response from this client library:
https://github.com/gmlewis/go-github/blob/master/github/apps.go#L23

If not, the next step is to try and figure out why.

**Comment by lollipopman** [comment]
Thanks, for some reason I was pinned to an old version, v17, which didn't have that field in the struct, after updating to v29.0.3, I get this error:
```
app, _, err := ghclient.Apps.Get(ctx, "")
GET https://github.<internal domain>.com/api/v3/app: 401 A JSON web token could not be decoded []
```
other calls work with the client, so I am not sure what the issue is. I assume it is something on my end with app permissions, but I can't find anything obvious in the github docs. If anyone has any thoughts it would be greatly appreciated

**Comment by gmlewis** [comment]
OK, supporting Enterprise GitHub user has historically been very challenging because everyone is running on a different version.

So the next step is determining what version of Enterprise GitHub you are using, and then post it here, and hopefully someone else using Enterprise GitHub will recognize the problem and tell you which version of this repo you need to pin to in order to get this back up and working again.

**Comment by lollipopman** [comment]
@gmlewis thanks for the reply, we are currently running, v2.20.1, which is the latest enterprise version.

**Comment by gmlewis** [comment]
OK, now please see if you can get the curl version of the API call to work, and maybe we can debug it.

**Comment by gmlewis** [comment]
Closing inactive issue for lack of activity/interest.  Feel free to reopen.
