### ISSUE TITLE
How to get all github repo's branches as a admin

### ISSUE THREAD

**Issue by pradeepkusingh** [google/go-github#1478]
Thanks for this great API, I am admin of a GHE and trying to get all repo and protected/unprotected branches, but unable to see all branches, only couple of repo shows few branches. Please help and provide me a sample which can provide all branches.

**Comment by gmlewis** [comment]
To answer this question, we first take a look at the GitHub Developers v3 API docs, and find the page relating to "Repositories / Branches":
https://developer.github.com/v3/repos/branches/

[List branches](https://developer.github.com/v3/repos/branches/#list-branches) sounds promising.

Then we see that if we omit the `protected` option, we should see _*all*_ branches.

Now we note that this endpoint uses: `GET /repos/:owner/:repo/branches`.

We can then switch to the go-github documentation and search for ListBranches:
https://pkg.go.dev/github.com/google/go-github/github?tab=doc#RepositoriesService.ListBranches

We can optionally look at the code and verify that it calls the same endpoint, which it does:
https://github.com/google/go-github/blob/v17.0.0/github/repos.go#L657

We can also note that the "protected" argument is not currently supported, so I will open a new issue.

Now it appears that you may have already found this endpoint, although you don't explicitly say that... so let's assume you did and are still not seeing all the branches.  Chances are high that your  GitHub Personal Access Token  doesn't have all the required permissions.

If that is the case, check out #1425 for a screenshot of what this should look like.

I hope that helps.  If you are still having problems, please give more detail so that someone can assist you.

**Comment by pradeepkusingh** [comment]
Thanks, I tried below and getting only few branches, as an admin I expect all branch should be lsited, but getting none of 1 or 2.

client.Repositories.GetBranch(ctx, user, *repo.Name, "")

**Comment by gmlewis** [comment]
`client.Repositories.GetBranch` should get one branch.
`client.Repositories.ListBranches` should get all branches.

OK, so first I could check if you get a different answer from `curl`, and if you still can't see all the branches, then please contact support@github.com and ask them why.

**Comment by pradeepkusingh** [comment]
ok, thank you :)
