### ISSUE TITLE
DeploymentStatus type does not contain all possible keys

### ISSUE THREAD

**Issue by jrossiter** [google/go-github#1494]
I'm using `go-github` in conjunction with GitHub Actions + Deployments. 
During deployments we update the deployment status and provide a `log_url` value that points back to the current GitHub actions URL.
We then use `github.Client.Repositories.ListDeploymentStatuses` to retrieve the statuses to retrieve the log URL.

There are a few issues that I can see:
1. The `ListDeploymentStatuses` method doesn't contain preview headers. (though `GetDeploymentStatus` does contain the headers)
2. The `DeploymentStatus` type doesn't have all available fields so if you provide the headers it won't parse them anyway.
3. The response body seems to be closed before its returned to the requester so we can't manually parse the raw JSON response.

**Comment by gmlewis** [comment]
Thank you @jrossiter for the report.  Yes, it looks like you are correct... would you like to submit a PR?
(Item # 3 should not be an issue once the first two items are resolved, agreed?)

If @jrossiter doesn't want to work on this issue, it would be a great one for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our CONTRIBUTING.md guide to get started.

Thank you!

**Comment by jrossiter** [comment]
Thanks @gmlewis, I can work on a PR.

Yes, #3 won't be an issue with the others resolved :)

**Comment by gmlewis** [comment]
Excellent!  Thank you, @jrossiter... it is yours.

**Comment by jrossiter** [comment]
@gmlewis PR created 👍
