### ISSUE TITLE
Repositories.ListByOrg doesn't return any of the allow* fileds

### ISSUE THREAD

**Issue by AlessioCasco** [google/go-github#1499]
Hello Guys!

## Context (Environment)
* go version go1.14 linux/amd64
With both:
  * github.com/google/go-github v17.0.0+incompatible
  * github.com/google/go-github/v29 v29.0.3

## Current Behavior
It seems that [func (*RepositoriesService) ListByOrg](https://pkg.go.dev/github.com/google/go-github/v29@v29.0.3/github?tab=doc#RepositoriesService.ListByOrg) does not return any of the `allow*` values listed here on the [repo type](https://pkg.go.dev/github.com/google/go-github/v29@v29.0.3/github?tab=doc#Repository).

`GetAllowMergeCommit()`, `GetAllowSquashMerge()` or `GetAllowRebaseMerge()` return false independently of the real value set on github side.

## Steps to Reproduce
`allRepos` from the bellow code doesn't have any of the `Allow*` fileds
```golang
opt := &github.RepositoryListByOrgOptions{
    ListOptions: github.ListOptions{PerPage: 50},
}

var allRepos []*github.Repository

// Retrieve all repos
for {
    repos, resp, err := client.Repositories.ListByOrg(ctx, github_org, opt)
    if err != nil {
        fmt.Printf("ERROR: %s\n", err)
        os.Exit(1)
    }
    allRepos = append(allRepos, repos...)
    if resp.NextPage == 0 {
        break
    }
    opt.Page = resp.NextPage
}
fmt.Print(allRepos)
```
## Expected Behavior
* `GetAllowMergeCommit()` or `GetAllowSquashMerge()` or `GetAllowRebaseMerge()` should return the real values present on github
* Raw data from the above code should return the real values present on github

Can you please let me know if you think I'm doing something wrong here?

Thanks
Alessio

**Comment by nightlark** [comment]
It looks like `allow*` values aren't returned with the `ListByOrg` function because the GitHub API to [List organization repositories](https://developer.github.com/v3/repos/#list-organization-repositories) is not returning them (and neither do the functions for listing by user or public repositories).

This might be a question you should ask support@github.com to see if not returning `allow*` values is a bug with the list by type APIs -- the only API for getting repositories I see that returns the values is [Get a repository](https://developer.github.com/v3/repos/#get-a-repository), which I think maps to the RepositoriesService Get function in go-github.

**Comment by AlessioCasco** [comment]
Thanks for your response, you are right actually, I was confused by their docs and understood that those values were supposed to be there.

Sorry to have wasted your time,
Alessio
