### ISSUE TITLE
Suspended GitHub App Installations

### ISSUE THREAD

**Issue by nightlark** [google/go-github#1517]
A new API was added for suspending GitHub app installations: https://developer.github.com/changes/2020-05-01-suspending-a-github-app-installation/

Suspend Installation: https://developer.github.com/v3/apps/#suspend-an-installation
Unsuspend Installation: https://developer.github.com/v3/apps/#unsuspend-an-installation

**Comment by gmlewis** [comment]
Thank you, @nightlark! 

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by joshuabezaleel** [comment]
May I have a shot on this one? :slightly_smiling_face:

**Comment by gmlewis** [comment]
Thank you, @joshuabezaleel!
It is yours.

**Comment by joshuabezaleel** [comment]
While I was browsing the docs, I also found that ["Delete an installation"](https://developer.github.com/v3/apps/#delete-an-installation) also hasn't been implemented yet. Should I added this to the to-do lists? @gmlewis
