### ISSUE TITLE
Organization Secrets

### ISSUE THREAD

**Issue by nightlark** [google/go-github#1525]
Organization secrets are here! https://github.blog/changelog/2020-05-14-organization-secrets/

I'll try to open a PR for this soon.

**Comment by gmlewis** [comment]
Although this ticket was assigned to you, @nightlark , it appears that @cj-taylor has gone ahead with a PR.  Are you OK with re-assigning this issue to @cj-taylor, or have you already invested a great deal of time into this one and are close to a PR?

I'm fine either way, as I know it can be frustrating to spend time on a PR and the work gets thrown away.

@cj-taylor - before you do this again in the future, please just add a comment to the issue you plan on closing, and we can coordinate ownership here so as to hopefully avoid this problem.

I took a quick glance at your PR and noticed that we need some file names to be changed, as we follow the naming of the GitHub Developer v3 API web pages, and not the naming of the API http paths. Additionally, required headers are missing.  Please see the CONTRIBUTING.md file for more details.

However, until we hear back from @nightlark, I'm going to hold off on reviewing your PR, and probably also wait until all the checkboxes are marked so that I can address it all at once.

**Comment by nightlark** [comment]
I have changes that are ready for a PR, I've just been waiting for a response from GitHub support on what I think is a docs issue.

**Comment by cj-taylor** [comment]
@gmlewis thanks for the guidance provided. I will gladly let @nightlark supersede my Pull Request with their changes. I'll make sure to communicate upfront before making future changes. I got here by working backwards from the terraform-provider-github working locally on the usage and thought I'd open it as an optional contribution to help out.

Either way, I'll gladly work on the terraform-provider-github related usage if that's okay!

**Comment by nightlark** [comment]
I opened a PR with the changes - there are some parts that are pretty different from #1532, so it's fine if that would be easier to use as the base for making changes.
