### ISSUE TITLE
Support "package" webhook event

### ISSUE THREAD

**Issue by patrickmarabeas** [google/go-github#1550]
Add support for the `package` webhook event.

Docs: https://developer.github.com/webhooks/event-payloads/#package

**Comment by gmlewis** [comment]
Thank you, @patrickmarabeas!

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by KevinMarioGerard** [comment]
Hi @gmlewis I would like to take this up. Will make a PR soon.

**Comment by ravindranrahul** [comment]
Hi @gmlewis ,

If this is still relevant, I would like to give this a try.

**Comment by gmlewis** [comment]
Thank you, @ravindranrahul!  It is yours.

**Comment by jeet-parekh** [comment]
@ravindranrahul, any updates on this?
