### ISSUE TITLE
Link to your documentation is missing

### ISSUE THREAD

**Issue by Pymann** [google/go-github#1561]
Can you put link: https://godoc.org/github.com/google/go-github/github
to your readme.md?

**Comment by gmlewis** [comment]
How about this instead?
https://pkg.go.dev/github.com/google/go-github/v32/github

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!
