### ISSUE TITLE
Remove some fields of IssueListCommentsOptions

### ISSUE THREAD

**Issue by you06** [google/go-github#1583]
`Sort` and `Direction` not work since GitHub changed its API.

https://developer.github.com/v3/repos/commits/#list-commits

https://github.com/google/go-github/blob/e881974953e6ab6d1a6a1610e98ed6401a3aa1ba/github/issues_comments.go#L37-L48

**Comment by gmlewis** [comment]
Thank you, @you06 !
The `Sort` and `Direction` fields need to be removed.  Although these apparently no longer are supported, this change is still a breaking API change, so I will mark it that way.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by juanri0s** [comment]
I can work on this! 😁

**Comment by gmlewis** [comment]
Thank you, @juanri0s !  It is yours.

**Comment by juanri0s** [comment]
@gmlewis I have removed the fields from the struct and the fields in the tests as well. Are we expecting this change in any other area other than `issues_comments.go`? Or do I need to go through the GH API docs and check myself?

**Comment by gmlewis** [comment]
These fields were identified in the issue. You are welcome to look through the docs for other discrepancies.

**Comment by tamalsaha** [comment]
@you06 @juanri0s @gmlewis @nightlark

Today I tried to update the client version and hit this issue. I am confused what is happening here. The OP points to the `list commits` api behavior changing. But the pr #1584 changed the `list comments` not `list commits` client. From what I can see the Github's api docs, these fields are still supported in the `list comments` api. https://docs.github.com/en/rest/reference/issues#list-issue-comments-for-a-repository .

I am confused what is happening here.

**Comment by gmlewis** [comment]
> I am confused what is happening here

Wow... It looks like I messed this one up big time... I apologize, @tamalsaha .

It looks like I need to revert #1584 and go back and change the correct struct.

Thank you for the report!

**Comment by gmlewis** [comment]
After further investigation, it turns out that this was an erroneous bug report.

Note that `ListCommits` does not have `Sort` or `Direction` fields and that there was no change to the GitHub API as was previously reported.

https://github.com/google/go-github/blob/master/github/repos_commits.go#L97-L116

Closing issue as incorrect and confusing.
