### ISSUE TITLE
Update Check Run HeadSHA

### ISSUE THREAD

**Issue by Adirio** [google/go-github#1652]
https://github.com/google/go-github/blob/1ff2714d8affd5ede5366bdb1a2d9472b669fe77/github/checks.go#L175-L186

Despite having an optional `HeadSHA` field, if you update this to a different commit hash it won't be updated.

We have some Check Runs that are PR-oriented and not commit-oriented and we were trying to use this field to rebind the Check Runs to the head commit of a PR on `synchronize`.

Is this a bug?

**Comment by gmlewis** [comment]
As far as I can tell from the official documentation: https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#update-a-check-run
the `head_sha` field is no longer accepted as a parameter and is completely ignored.

You may wish to contact GitHub technical support and ask them the same question.

**Comment by Adirio** [comment]
+1 to removing it from the `UpdateCheckRunOptions` struct to prevent further confussion.

**Comment by gmlewis** [comment]
The other fields should be verified as well as part of addressing this issue.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by ishanupadhyay** [comment]
Hi @gmlewis  @Adirio  I can work on this issue

**Comment by ishanupadhyay** [comment]
Please take a look at [PR-165 7](https://github.com/google/go-github/pull/1657) . It will be my first contribution to this project :)
