### ISSUE TITLE
Is the methods of github.Client thread-safe?

### ISSUE THREAD

**Issue by Zamiell** [google/go-github#1673]
Greetings,

I want to share a github.Client between multiple goroutines.  Is it safe to do so?

In order to answer this question, I surfed to [the documentation for this library](https://pkg.go.dev/github.com/google/go-github/v33), and searched for "goroutine", "thread-safe", "thread safe", and "safe". All of these searches turned up 0 results. Please add this information to the documentation. Thank you.

**Comment by gmlewis** [comment]
Yes, this is safe, but doing so is a really easy way to quickly cause rate limit and abuse errors.
Believe me when I say I have experience in these areas. 😄 

Make sure you review and understand the GitHub API policies first:

* https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#rate-limiting
* https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#abuse-rate-limits
* https://docs.github.com/en/free-pro-team@latest/rest/guides/best-practices-for-integrators#dealing-with-abuse-rate-limits
* https://docs.github.com/en/free-pro-team@latest/rest/guides/best-practices-for-integrators#dealing-with-rate-limits

**Comment by Zamiell** [comment]
Thank you for the quick response. Yes, rate limits are already clearly documented in the README.md. But thread-safeness is not. Can we add it?

**Comment by gmlewis** [comment]
It's been years since I tested thread-safeness, so I'm a bit leery of adding it right now.  Additionally, this is the first request in many years of use, so I'm not sure this is a high-demand feature.

Feel free to validate that the repo is thread-safe (ideally by writing unit tests) and then present a PR for how you would like the README.md to be updated based on your findings.
 
Thank you.

**Comment by gmlewis** [comment]
Closing inactive issue for lack of activity/interest.
