### ISSUE TITLE
Implement actions billing endpoint

### ISSUE THREAD

**Issue by cpanato** [google/go-github#1788]
Hello

I might overlook but did not find the actions billing endpoint

https://docs.github.com/en/rest/reference/billing#get-github-actions-billing-for-an-organization

This is something we are considering to add?

cc @gmlewis

**Comment by gmlewis** [comment]
Thank you, @cpanato - it looks like we don't yet support this endpoint (and possibly others on this page as well).

Whoever volunteers to address this issue should research if there are other billing endpoints that need to be added.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by cpanato** [comment]
@gmlewis ok, thanks for your reply
I can work on that if you are not against

**Comment by gmlewis** [comment]
Thank you, @cpanato ! This issue is yours.
