### ISSUE TITLE
Return TotalCount in ListRepos in AppsService

### ISSUE THREAD

**Issue by victor88121** [google/go-github#1791]
`ListRepos` currently only returns the list of repositories from github's response but not the total_count ([Link](https://docs.github.com/en/rest/reference/apps#list-repositories-accessible-to-the-app-installation)). This total_count is different from just the length of the list of repositories returned if the number of repositories in the installation is greater than the per_page pagination limit set in the request. Is it possible to add it for ListRepos to return?

**Comment by gmlewis** [comment]
Ah, yes, I see that it was originally written this way in #436 and I unfortunately didn't catch it at the time.

Yes, I think we can easily add the field by making a new return struct, which would be a breaking API change.
I'll open this issue up to volunteers.  Thanks, @victor88121.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by DarthBenro008** [comment]
Hey @gmlewis, 
I would like to work on this issue, could you please assign me this issue, if that's alright?

**Comment by gmlewis** [comment]
Thank you, @DarthBenro008 !  It's yours.
