### ISSUE TITLE
Feature request: fs.FS implementation

### ISSUE THREAD

**Issue by carlmjohnson** [google/go-github#1792]
Now that Go 1.16 has an io/fs.FS interface for file systems, it would be nice if you could drop in a GitHub repo as a file store.

**Comment by gmlewis** [comment]
Thank you, @carlmjohnson .

Since this repo is dedicated to supporting the GitHub v3 API, I'm wondering if your suggestion might fit more nicely into a separate helper package outside this repo? I believe the API supports everything that is needed to accomplish this.

I'm recommending a separate repo+package due to the added maintenance burden on this repo, which is supported completely by volunteers.

I'm open to discussion, though.

**Comment by carlmjohnson** [comment]
With any web API library, there’s a question of do you make it a thin layer over the endpoints or a thick client that abstracts the plumbing away. This library is not a completely dumb thin layer—for example, it hides all the base64 stuff—but it is closer to a thin client than a thick one. I think it probably makes sense to let another package do an experimental FS layer for now and then maybe come back in a year or two if that turns out to be a good idea.

**Comment by dmitshur** [comment]
I agree this is tempting to provide.

One reason not to provide it would be because a simple implementation would not scale well, and an implementation that scales well would be too large and complex to add to this API wrapper.

Consider a large GitHub repository with hundreds of MB of content. Accessing a large file more than once would either have to reach out to the GitHub API each time or use a cache to avoid unnecessary remote calls. Whether to use a cache, and what kind of cache, depends on the requirements of the caller. Is this a simple code example or one-off utility? Is it a long running service that is limited on memory?

It was possible to implement a virtual filesystem with an interface before `io/fs` as well, consider `net/http.FileSystem` or a custom interface. `io/fs` helps with standardization. If it wasn't a good idea to expose a GitHub repository as an `http.FileSystem` before, it's likely not a good idea to start now, and vice versa, if a custom vfs interface was used previously, then now is a good time to consider migrating to `io/fs`.

The https://github.com/sourcegraph/vcsstore project was about making VCS repositories accessible over HTTP, including support for file access via a `FileSystem` interface (see [here](https://pkg.go.dev/sourcegraph.com/sourcegraph/go-vcs/vcs#Repository.FileSystem)). The large API surface of [`vcsclient`](https://pkg.go.dev/sourcegraph.com/sourcegraph/vcsstore/vcsclient) shows some of the complexity and considerations that become needed when attempting to use it in practice.

**Comment by gmlewis** [comment]
Closing issue in deference to external helper repo implementation.
