### ISSUE TITLE
replace []Issue with []*Issue

### ISSUE THREAD

**Issue by rsc** [google/go-github#180]
In general having slices of large structs is awkward because it means that when you range over the slice, you either have to write:

    for i := range list {
        x := &list[i]
        ...
    }

or you write

    for _, x := range list {
        ...
    }

and put up with the fact that (1) the iteration is doing a (more expensive than pointer copy) struct copy  for each element and (2) you cannot modify the elements by changing x, since x is a copy.

If list were a []*github.Issue it wouldn't have these problems. 

The encoding/json package can handle slices of pointers just fine, but changing the types would have the drawback of breaking existing clients.

**Comment by gmlewis** [comment]
While scanning through the old issues, I just found this one and think it is worthwhile doing since this package is frequently handling slices of large structs.

I'm thinking that the impact on existing clients will be negligible due to the nice inference properties of Go.

@willnorris and @shurcooL - I would like to do this... any objections?

**Comment by shurcooL** [comment]
SGTM. This looks like an improvement, and updating for API change is easy (in most cases, no changes need to be done).
