### ISSUE TITLE
Audit Log API Returns Non-Standard Timestamp

### ISSUE THREAD

**Issue by lindluni** [google/go-github#1849]
The GitHub Audit Log API return a Unix timestamp in milliseconds, which the current timestamp unmarshalJSON implementation in go-github does not take into account. An implementation needs to be added to account for the audit log having a millisecond-based timestamp.

**Comment by gmlewis** [comment]
Thank you, @lindluni !  This could be handled probably in several different ways... I might simply modify `github/timestamp.go` to check if the parsed timestamp is "sane", and if not, see if parsing it as if it were milliseconds since epoch returns a "sane" timestamp... but I'm open to other ideas.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!
