### ISSUE TITLE
ValidatePayload does not correctly parse mime type from Content-Type header

### ISSUE THREAD

**Issue by shmyer** [google/go-github#1874]
When validating webhook payloads the `Content-Type` header is compared in a switch statement with either `application/json` or `application/x-www-form-urlencoded`

https://github.com/google/go-github/blob/0318e77f5741866b7870eb4c45daacd2d7d95af3/github/messages.go#L157-L206

This is not working for Content-Type headers which contain for example a charset, resulting in those webhooks being rejected:
`Content-Type: application/json; charset=UTF-8`

The correct way to validate the mime type might look something like this:

https://gist.github.com/rjz/fe283b02cbaa50c5991e1ba921adf7c9

**Comment by gmlewis** [comment]
Thank you, @shmyer - would you like to work on this issue and provide a PR, or would you like me to open up this issue to all volunteer contributors to this repo?

**Comment by shmyer** [comment]
@gmlewis I don't have any experience with go, so please feel free to open up the issue :)

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Note that this PR will require some very careful testing, as this is a change in behavior where we don't want to break any existing clients.

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by sagar23sj** [comment]
Hi @gmlewis. I would like to work on this issue.

Just wanted to clarify one thing before starting. Do we just need to handle the parameters if they are present in content-type?
For example, in the case of  Content-Type: application/json; charset=UTF-8, I just need to check that the content type has valid parameters with mime type??

I hope my question is clear.
Thanks

**Comment by gmlewis** [comment]
> Just wanted to clarify one thing before starting. Do we just need to handle the parameters if they are present in content-type?
> For example, in the case of Content-Type: application/json; charset=UTF-8, I just need to check that the content type has valid parameters with mime type??

Yes, that's correct. We had never seen the `charset` being passed back from GitHub before, and maybe this is a recent change.
In your PR you need to just make sure that if `charset` is included, that the existing checks still are handled correctly.
In other words, the presence of `; charset=...` should not break anything.

I took a look at this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type
and I don't think we need to expect anything else.  

One (simple and hopefully robust) way to handle it might be simply to split on a semicolon (`;`) and ignore everything after it.
Then the remaining code can be used unaltered.

**Comment by sagar23sj** [comment]
Hi @gmlewis . I am a little confused with how to test for a success case, i.e case in which content type is application/json; charset=UTF-8. Since there are many success test cases already present, I am not sure how should I go about writing test cases for a success scenario.

Should I update those test cases and add parameters in content-type string or should I replicate the existing test cases and  add parameters to content type string.

Thanks
