### ISSUE TITLE
Not able to get the labels for a repo

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [google/go-github#1877]
There does not appear to functions to get all the labels for a repo. The only way to do it is through the issue service. Ideally, there should be a way to get the labels of a repo without needing to use `client.Issues.ListLabels()`.

I can work on a PR for this.

**Comment by gmlewis** [comment]
Are you perhaps looking for this:
https://github.com/google/go-github/blob/master/github/issues_labels.go#L28-L50
?

**Comment by gmlewis** [comment]
GitHub v3 API docs: https://docs.github.com/en/rest/reference/issues#list-labels-for-a-repository

**Comment by Cyb3r-Jak3** [comment]
I am looking for something that is more like `client.Repositories.ListLabels` as I feel the way with the issue service is oddly named.

**Comment by willnorris** [comment]
Yeah, I could understand expecting this to be part of the RepositoriesService rather than the IssuesService.  We follow the way GitHub splits up endpoints in their documentation.  In this case, it's part of the Issues docs (the URL @gmlewis provided above), not part of the [Repos docs](https://docs.github.com/en/rest/reference/repos).  But it does list all issue labels for a repo, which I think is what you were looking for.

**Comment by Cyb3r-Jak3** [comment]
Gotcha. I made a quick PR that basically would translate the `RepoistoriesService` into the `IssuesService`.  Don't if I should just close it out and handle the conversation on the client side.

**Comment by willnorris** [comment]
Since this functionality already exists in the library (even if it's not where you might initially expect), I don't think it makes sense to duplicate these methods across different services.  

So yes, if this is something you can handle client side, that sounds like the way to go.  (Though, I'm honestly curious why having these on the `RepositoriesService` rather than the `IssuesService` matters at all)

**Comment by Cyb3r-Jak3** [comment]
Sounds good. Appreciate the quick responses!
