### ISSUE TITLE
Add support for updated starring API

### ISSUE THREAD

**Issue by willnorris** [google/go-github#188]
Announcement: https://developer.github.com/changes/2014-12-09-new-attributes-for-stars-api/

**Comment by rubenvereecken** [comment]
I'd like to tackle this one to get a feel for the project. I've already tracked the location of the code currently responsible for listing a user's starred repositories.

What would be the best way to support the new attributes (currently just `starred_at`)? GitHub allows a custom `Accept` header to request a different format. My guess would be to have this behavior controlled by the `ActivityListStarredOptions`, but the problem is that the returned object is now not an array of repositories anymore. Maybe an extra function `ListStarredWithDates` or similar?

**Comment by willnorris** [comment]
yeah, this should be a good issue to get started with.  Most of the time with preview APIs like this, we just enable them by default if we can and don't bother adding an option for it.  In this particular case, it seems kinda silly that they put this behind a custom media type at all, since all it seems to be doing is adding a single field in the response to a single method.

Take a look at how this was done for the licenses API, and follow the same approach: https://github.com/google/go-github/search?q=mediaTypeLicensesPreview

 - define a new var with the new media type
 - update the relevant methods to set that as the accept header on requests (and add a TODO comment to remove it when it's no longer needed)
 - update tests to check for the presence of that media type

**Comment by willnorris** [comment]
fixed in #199
