### ISSUE TITLE
Pagination util (feature request)

### ISSUE THREAD

**Issue by g4s8** [google/go-github#1935]
Hi. I frequently use this library in my projects. When working with list operations, I'm writing a lot of similar code, like this:
```go
opt := new(github.ListOptions)

for {
	res, rsp, err := cli.SomeListOperations(args, opts)
        // handle error
	if rsp.NextPage == 0 {
		break
	}
        // process rsp
	opts.Page = rsp.NextPage
}
```

In one project, I created pagination util to refactor such code into:
```go
opt := new(github.ListOptions)
pagination := new(pagination)

for pagination.moveNext(opts) {
	res, rsp, err := cli.SomeListOperations(args, opts)
        // handle error
	pagination.update(rsp)
        // process rsp
}
```
The source code is available here: https://github.com/g4s8/gitstrap/blob/master/internal/gitstrap/pagination.go

This util automatically update `ListOptions` next page from accumulated `Response` page properties, and return `true` if next page exist to use it in `for` loop.

I think that such kind of tool is more convenient than manual operations on response and page options, what do you think? If you agree, I'm ready to submit a PR.

**Comment by gmlewis** [comment]
Hi @g4s8 - thanks for the recommendation.

Normally, we let users of this repo write their own helper utility functions since they can range quite a bit in what they accomplish.

As a maintainer of the repo, I get concerned when we add things like this and then users want to tweak the utility functions to do things that they find useful... and the maintenance burden and surface area of supported code increases... so I prefer to keep these out of the repo in general.

However, let's leave this issue open to see if there is any interest.

If there is no interest in a couple weeks, we'll close the issue and not add the utility methods.
If there is interest, however, I'm happy to entertain a PR.

**Comment by gmlewis** [comment]
Closing for lack of interest/activity. Feel free to comment or reopen if there indeed is more interest.

**Comment by aaomidi** [comment]
FWIW I think this would be a nice addition. It might even get easier to do this with Generics. Although, with Generics it'd also be pretty easy for the user of this library to just implement it too \o/

**Comment by gmlewis** [comment]
> FWIW I think this would be a nice addition. It might even get easier to do this with Generics. Although, with Generics it'd also be pretty easy for the user of this library to just implement it too \o/

True, and as much as [I love generics](https://github.com/gmlewis/advent-of-code-2021), I doubt this repo will be using them any time soon since we have so many legacy systems using it. But I could also be wrong.

**Comment by beanaroo** [comment]
I'm enjoying this library but also find myself wrapping all list operations in duplicate functions for pagination. I'm sure generics will help me reduce those.

Coming from the [Python GitLab library](https://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination), having pagination taken care of was really convenient:
`projects = gl.projects.list(all=True)`.

Doing pagination myself is not particularly _inconvenient_ either. I just came here to see if I was missing out on anything already provided.
