### ISSUE TITLE
Subscriber Count Always 0

### ISSUE THREAD

**Issue by jstigter-beep** [google/go-github#1993]
I am fetching the repositories belonging to an organization, and I have noticed that the subscribers count is always 0. I have done several tests where I will watch and unwatch a repository and then checking a call to the github API using v37 of go-github and then directly call the API. The direct call was always accurate, matching the actual watch count, and go-github always returned 0. I investigated further and found that the `SubscribersCount` property of `github.Repository` is always `nil` which is why the subscriber count is 0. The rest of the code functions as expected; I retrieve all the expected repositories and all their other attributes are correct. Any help in resolving this issue is greatly appreciated.

Example repository used: https://github.com/jstigter-test/cool

Github API call checked against: https://api.github.com/repos/jstigter-test/cool

Code snippet used to retrieve the repositories for an organization: `repos, _, err := g.Client.Repositories.ListByOrg(...)`

Code snippet to retrieve the subscribers: `watchersCount := repo.GetSubscribersCount()`

Package imported: `github.com/google/go-github/v37/github`

**Comment by gmlewis** [comment]
Note that when making comparisons between the GitHub API direct calls and using this library, you need to use the exact same endpoint to determine if this library is working correctly.

Therefore, the call you should be using for comparison is this one: https://github.com/google/go-github/blob/master/github/repos.go#L416-L419

which is a `GET /repos/jstigter-test/cool`.

Please try this instead of `ListByOrg` and report back your findings.

**Comment by gmlewis** [comment]
The reason I say this is because the GitHub API is known to not always populate all fields in all possible API calls that return a particular struct (such as `Repository`).  Whenever there is doubt, you should read the GitHub API docs directly (which we add links to from this repo).

In this library, we reuse structs for multiple purposes instead of attempting to make exact matches for each possible API call and the fields that the official API chooses to return.  This is a matter of practicality.

**Comment by jstigter-beep** [comment]
I switched to a singular API call to retrieve the repository and the `SubscribersCount` was correct. Thank you for explanation, and I will read through there in the future.

Thanks!
