### ISSUE TITLE
Feature: Add support for autolinks

### ISSUE THREAD

**Issue by lsowen** [google/go-github#2044]
`autolinks` support was recently added to the rest api.   Announcement: https://github.blog/changelog/2021-08-02-apis-for-autolinks/

This would be super useful to allow automated management of autolinks via API.

Docs: https://docs.github.com/en/rest/reference/repos#autolinks
More info: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/configuring-autolinks-to-reference-external-resources

**Comment by gmlewis** [comment]
Thank you, @lsowen  !

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by alexal** [comment]
@gmlewis I would like to work on this, please.

**Comment by gmlewis** [comment]
> @gmlewis I would like to work on this, please.

Thank you, @alexal !  It's yours.

**Comment by alexal** [comment]
Thank you, @gmlewis. Please review PR #2046 when you have time.

**Comment by alexal** [comment]
@gmlewis I apologize, I missed one of your comments, this is why I made two additional commits. I've implemented all the changes you have requested. Looks better now?
