### ISSUE TITLE
Support  "Rename a branch"

### ISSUE THREAD

**Issue by vlsokol** [google/go-github#2118]
Is there a plan for adding branch renaming feature: https://docs.github.com/en/rest/reference/repos#rename-a-branch?

**Comment by gmlewis** [comment]
Yes indeed, and thank you @vlsokol for the report... it looks like we haven't implemented it yet.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by tamboliasir1** [comment]
could you give a bit of an insight or how to start with it? If I get a little help, I guess I will be able to work on it. This will be my first PR.

**Comment by vlsokol** [comment]
@tamboliasir1, resolved - https://github.com/google/go-github/pull/2119. Waiting for it to be merged.
