### ISSUE TITLE
unmarshal error in billing.go - GetStorageBillingOrg function

### ISSUE THREAD

**Issue by gpkmr-genesys** [google/go-github#2203]
Hello - Am trying to get the storage stats for my GitHub org from GetStorageBillingOrg function, But it throws error.
Details as follows.

_Go version used_: go1.17.2 linux/amd64
_Operating system_: Ubuntu
_Function reference_: https://github.com/google/go-github/blob/master/github/billing.go#L79

_Error_:`json: cannot unmarshal number 19.5361328125 into Go struct field StorageBilling.estimated_paid_storage_for_month of type int`

The output is on float but the struct field is of type int
https://github.com/google/go-github/blob/master/github/billing.go#L41-L45

Below is my custom function code:
```
func storage(ctx context.Context, client *github.Client, org string) {
	str, _, err := client.Billing.GetStorageBillingOrg(ctx, org)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(str)
}
```
Am able to get the response from GitHub API though
```
curl -s -u $gituser:$token -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/$org/settings/billing/shared-storage
{
  "days_left_in_billing_cycle": 16,
  "estimated_paid_storage_for_month": 19.4375,
  "estimated_storage_for_month": 69
}
```

**Comment by gmlewis** [comment]
Thank you for the report, @gpkmr-genesys !
It looks like that field needs to be changed from `int` to `float64`.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by gunadhya** [comment]
Hi @gmlewis, I'd like to work on this issue. Could you assign it to me?

**Comment by gmlewis** [comment]
> Hi @gmlewis, I'd like to work on this issue. Could you assign it to me?

Thank you, @gunadhya !  It is yours.

**Comment by gpkmr-genesys** [comment]
@gmlewis - I would like to work on it since it will be my first contribution. Since @gunadhya has already taken it up, am good with it.

**Comment by gmlewis** [comment]
> @gmlewis - I would like to work on it since it will be my first contribution. Since @gunadhya has already taken it up, am good with it.

I apologize, @gpkmr-genesys - I should have offered it to you first.  :disappointed:

**Comment by gpkmr-genesys** [comment]
@gmlewis - No problem :-)  All we need is to fix the issue. Glad that I have made some contribution by identifying a defect.
