### ISSUE TITLE
Support additional GitHub pages update parameters

### ISSUE THREAD

**Issue by pkwarren** [google/go-github#2261]
The https://pkg.go.dev/github.com/google/go-github/v41/github#RepositoriesService.UpdatePages API only currently supports updating the CNAME and source properties: https://github.com/google/go-github/blob/178169fc04bc4a05ca48f98709cdd02ab5b556e3/github/repos_pages.go#L90-L98

There are additional parameters which would be useful for consumers (i.e. terraform provider) to be able to update (see https://docs.github.com/en/rest/reference/pages#update-information-about-a-github-pages-site for reference):
* https_enforced
* public

**Comment by gmlewis** [comment]
Thank you, @pkwarren !

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!
