### ISSUE TITLE
Documentation of CreateWorkflowDispatchEventByID Doesn't Match GitHub REST API Docs

### ISSUE THREAD

**Issue by kylekurz** [google/go-github#2262]
In `actions_workflows.go`, the [`CreateWorkflowDispatchEventRequest`](https://github.com/google/go-github/blob/master/github/actions_workflows.go#L51-L54) type lists the following documentation of the `Ref` argument:

```
// Ref represents the reference of the workflow run.
// The reference can be a branch, tag, or a commit SHA.
// Ref is required when creating a workflow dispatch event.
Ref string `json:"ref"`
```

However, [GitHub's REST API](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event) restricts that ref to just a branch or tag name. We initially thought we could build against a specific commit due to this documentation, but further investigation after a failure shows that's not accurate:

```
ref | string | body | Required. The git reference for the workflow. The reference can be a branch or tag name.
```

**Comment by gmlewis** [comment]
Thank you, @kylekurz !  So it sounds like the comment needs to be updated to match the official docs.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by kylekurz** [comment]
Thanks @gmlewis, happy to throw a PR at you for just editing that comment to match GitHub's docs. I'll tackle that this afternoon.
