### ISSUE TITLE
missing InstallationRepositoriesEvents accessors

### ISSUE THREAD

**Issue by devinburnette** [google/go-github#2265]
I have a github app that subscribes to certain webhook events. The `installation_repositories` event has the following fields in the event types stuct:
```go
type InstallationRepositoriesEvent struct {
	// The action that was performed. Can be either "added" or "removed".
	Action              *string       `json:"action,omitempty"`
	RepositoriesAdded   []*Repository `json:"repositories_added,omitempty"`
	RepositoriesRemoved []*Repository `json:"repositories_removed,omitempty"`
	RepositorySelection *string       `json:"repository_selection,omitempty"`
	Sender              *User         `json:"sender,omitempty"`
	Installation        *Installation `json:"installation,omitempty"`
}
```
However, it appears that there are no accessors for accessing RepositoriesAdded and RepositoriesRemoved. I'm going to make an attempt at adding them in a subsequent PR, if that's okay. Thanks!

**Comment by gmlewis** [comment]
> However, it appears that there are no accessors for accessing RepositoriesAdded and RepositoriesRemoved. I'm going to make an attempt at adding them in a subsequent PR, if that's okay. Thanks!

Actually, @devinburnette, all accessors are auto-generated, so a PR will not work.

Since these fields are slices, there is no need for accessors, as you can use them directly.

Accessors are handy when something might be `nil` and you want to return the zero-value of the field whether it is `nil` or not.
Slices already have a zero value of `nil` and therefore don't need an accessor.

I hope this helps.
