### ISSUE TITLE
Please add security_advisory and code_scanning_alert event types

### ISSUE THREAD

**Issue by uptycs-rmack** [google/go-github#2306]
These two event types would be very useful to be able to receive through the webhook API.

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#security_advisory

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#code_scanning_alert

Thanks, Ryan

**Comment by gmlewis** [comment]
> I'm fairly new to golang so I'm not my first choice to work on this but if you don't think there would be much interest from anyone else on it I'm sure I can muddle though. What would you recommend?

Thanks, @uptycs-rmack - no need to muddle through... we have lots of eager contributors to this repo who are happy to help out.  I'll open it up.

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by gmlewis** [comment]
> @gmlewis I will be more than happy to work on this.

Thank you, @sourikghosh ! It's yours.

**Comment by uptycs-rmack** [comment]
Thank you @gmlewis  and @sourikghosh!
