### ISSUE TITLE
Support "Sync a fork branch with the upstream repository"

### ISSUE THREAD

**Issue by lkxed** [google/go-github#2335]
API doc here: https://docs.github.com/en/rest/reference/branches#sync-a-fork-branch-with-the-upstream-repository.

**Comment by gmlewis** [comment]
Thank you, @lkxed .

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by lkxed** [comment]
@gmlewis Wow, that's great. I am still learning Go and new to this project. I'd love to try adding this API. Could you assign this issue to me? Thanks for your warm welcome!

**Comment by gmlewis** [comment]
> @gmlewis Wow, that's great. I am still learning Go and new to this project. I'd love to try adding this API. Could you assign this issue to me? Thanks for your warm welcome!

Absolutely, @lkxed ... it is yours! :smile:

**Comment by gmlewis** [comment]
> I am surely missing something but since I am new to Go and its testing, I just don't know what...

Hi @lkxed , this can definitely be confusing if you are new to Go and its testing framework... I remember being confused about this very thing.

It turns out that our unit testing framework actually fires up a test http web server in-memory and starts making requests against it. It is your job to return a valid response in that test that will then be unmarshaled into a Go struct, so chances are high that you simply need to craft a JSON response that is appropriate for what you are testing.

To learn more about this, please read through this page: https://pkg.go.dev/net/http/httptest
It is actually a quick read, and will give you much greater insight into what is happening under the hood.

If you are still having problems, please go ahead and create a PR and then we can comment back-and-forth on the PR itself and I can show you how to build a JSON response that is appropriate for what you are testing.

**Comment by lkxed** [comment]
@gmlewis Thanks for guidance! It makes sense to me now. It turns out I've forgotten to change the test endpoint from to my own `/repos/o/r/merge-upstream` after I copy it from others. I now pass the unit test! Do I need to do fields & integration test as well? If not, I am prepared to create a PR.

```
ok      github.com/google/go-github/v43/github  0.558s
?       github.com/google/go-github/v43/test/fields     [no test files]
?       github.com/google/go-github/v43/test/integration        [no test files]
```

By the way, I notice two files `github-accessors.go` & `github-accessors.go` are generated, and they are not excluded in `.gitignore` file. Should I commit them as well?

**Comment by gmlewis** [comment]
Glad to hear it, @lkxed !

No, you don't need to do fields and integration tests.

Yes, once you run `go generate ./...` you must add the modified files to the PR in order for all the tests to pass.

**Comment by lkxed** [comment]
Hi @gmlewis , I've finally raised a PR. Could you review it some time? Thanks again for all the help!
