### ISSUE TITLE
Is there a place to mention projects built on google/go-github?

### ISSUE THREAD

**Issue by cbrgm** [google/go-github#2347]
Hey 👋 , 

as the title says I would like to ask if there is a place to mention projects that are built on [google/go-github](https://github.com/google/go-github). For example an `ADOPTERS.md` like at [prometheus-operator/prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/blob/main/ADOPTERS.md). 

In the README some projects are mentioned like 

* [github.com/shurcooL/githubv4](https://github.com/shurcooL/githubv4)
* [github.com/bradleyfalzon/ghinstallation](https://github.com/bradleyfalzon/ghinstallation)

Background is that I wrote a Go module ([cbrgm/githubevents](https://github.com/cbrgm/githubevents)) for Github Webhook Events that relies heavily on go-github to make consuming events easier similar to [octokit/webhooks.js](https://github.com/octokit/webhooks.js).

Please don't get me wrong, I don't want to abuse go-github for self-promotion, I just thought it might be helpful for some people if something like this is mentioned somewhere. 

If that's not the case, feel free to close the issue. I am very thankful for answers! 😃

**Comment by gmlewis** [comment]
Cool, @cbrgm !  Happy to hear that it is useful to you!
We don't have anything like that at the moment, but I'll defer this question to @willnorris to make the final call.
(I think it might be cool to have, for the record, but there may be other considerations that need to be taken into account that I'm not aware of.)

**Comment by willnorris** [comment]
I'm fine continuing to list projects that, like githubv4 and ghinstallation, are specifically related to go-github and are likely to be useful for go-github users.  At first glance, githubevents seems to fit that description, so I'd have no problem adding it to the README somewhere.

I'm not sure that I'd want to try and maintain an adopters.md file, since at his point that list would be quite large.  The unversioned package alone [lists 3800+ importers](https://pkg.go.dev/github.com/google/go-github/github?tab=importedby).  We could list some of the larger adopters, but I'm not sure there'd be a lot of value, since the library is pretty well established already.

**Comment by cbrgm** [comment]
Thank you @gmlewis and @willnorris  for your feedback! 👍 I understand the concerns, maybe an `Adopters.md` is not the best approach for something like this because there would probably be too many. 

Is there already a place in the README where the project would fit in? I would be very happy to provide a PR. I would also have no problem donating [cbrgm/githubevents](https://github.com/cbrgm/githubevents), as I really appreciate go-github and the work that goes into it.

**Comment by gmlewis** [comment]
Feel free to create a new section in the README.md file in your PR where you think it is appropriate and we can discuss the details there. 😁

**Comment by cbrgm** [comment]
Will do so, thanks!
