### ISSUE TITLE
IssuesService.Edit cannot clear an issue's milestone

### ISSUE THREAD

**Issue by tchap** [google/go-github#236]
Much like #181 I fail to see how to use go-github to clear an issue's milestone. The API requires the milestone be to set to `null` in the request so that it is cleared, but that is not possible since the field uses `omitempty`.

Not sure what the right solution would be, perhaps a standalone method for clearing milestones?

**Comment by tbruyelle** [comment]
Is there a workaround for this ? 
If no I think a dedicated method is the way to go, something like `RemoveMilestonelForIssue`, I can work on this.

**Comment by tchap** [comment]
The workaround is to send the request manually. You can basically copy `EditMilestone` and put your own struct there.

**Comment by tbruyelle** [comment]
Indeed, we can workaround it like that (tested) : 

```go
       u := fmt.Sprintf("repos/%v/%v/issues/%d", owner, repo, issue)
       req, err := githubCli.NewRequest("PATCH", u, &struct {
               Milestone interface{} `json:"milestone"`
       }{})
       if err != nil {
               return err
       }
       _, err = githubCli.Do(req, nil)
       if err != nil {
               return err
       }
```

**Comment by e-beach** [comment]
I'm surprised this hasn't been addressed in 2 years, though it's clear it's a problem as @marun has mentioned. Should we add a `removeMilestone` method to the `IssuesService`?

**Comment by shurcooL** [comment]
I think that's the case because the GitHub API is very large, and removing a milestone from an issue is something only a few people ever need. It has a well described workaround here, so those who need it use that and move on.

To resolve the issue, we need to come up with a good API/good way of doing so.

**Comment by alexellis** [comment]
Nice to see @elliott-beach again - this issue manifests as a bug with much head scratching and wasted time. Perhaps now that there are multiple consumers with this specific issue, we could fix this issue using this library. What are your thoughts 3 years on?

Alex

**Comment by gmlewis** [comment]
It seems to me to be a relatively simple matter to resolve this issue by creating a new `RemoveMilestone` method with the [workaround above](https://github.com/google/go-github/issues/236#issuecomment-220560052).

Leaving this issue open.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by sagar23sj** [comment]
Hi @gmlewis, i would like to this work on this issue.
Thanks

**Comment by gmlewis** [comment]
> Hi @gmlewis, i would like to this work on this issue.

Thank you, @sagar23sj, it is yours.

**Comment by AGMETEOR** [comment]
Hi @sagar23sj , in case you're busy I would like to take this off your plate :)

**Comment by AGMETEOR** [comment]
Thanks @sagar23sj for letting me take this up. I'll start work on it over the weekend when I get some personal time.

**Comment by AGMETEOR** [comment]
Still on it...
