### ISSUE TITLE
Support for Polling in ActivityService

### ISSUE THREAD

**Issue by bithavoc** [google/go-github#242]
Since the activityservice is based in the [events](https://developer.github.com/v3/activity/events) endpoint we'd should be able to support `Etag` and `X-Poll-Interval`.

As [documentation](https://developer.github.com/v3/activity/events) says:

> Events are optimized for polling with the “ETag” header. If no new events have been triggered, you will see a “304 Not Modified” response, and your current rate limit will be untouched. There is also an “X-Poll-Interval” header that specifies how often (in seconds) you are allowed to poll. In times of high server load, the time may increase. Please obey the header.

We'd need to somehow fit `Etag` as a new field of `ListOptions struct` and `PollInterval` as part of `Response struct`, candidate methods for such options are `ListEvents`, `ListEventsReceivedByUser` and `ListIssueEventsForRepository`, etc.

Instead of adding these new fields to `ListOptions` and `Response`, we could have `PollableListOptions` and `PollableResponse` with new versions of functions that enables polling like `PollListEvents` and `PollListEventsReceivedByUser` using these new types `PollableListOptions` and `PollableResponse`... or we can just change the signature and break current clients hehe.

any thoughts on the approach, naming, etc?

**Comment by glorieux** [comment]
:+1: I've ran into that exact use case.

I think option two is the best as it would not add extra fields to `ListOptions` and `Response` and users will then be able to select between a regular request like ListEvents or a pollable one based on their needs.

**Comment by willnorris** [comment]
Yes, using a custom options type is the right way to go here, and is used throughout the library.  Following the existing naming conventions, I would probably name it `EventListOoptions` or `ListEventOptions` or something like that.

As for the `X-Poll-Interval` header, you don't need a custom type for that... you can already fetch any response header from the existing Response type since it has the raw http.Response inside of it: `resp.Response.Header.Get("X-Poll-Interval")`.  I *guess* we could add a Header method so that could be shortened to `resp.Header.Get("X-Poll-Interval")`, but I probably wouldn't do much more than that.  And even that really seems unnecessary.

**Comment by bradfitz** [comment]
I just ran into this too. I currently do this in a loop:

```go
                issues, _, err := p.ghc.Issues.ListByRepo(ctx, owner, repo, &github.IssueListByRepoOptions{
                        State:     "all",
                        Sort:      "updated",
                        Direction: "desc",
                        Since: since,
                        ListOptions: github.ListOptions{
                                Page:    page,
                                PerPage: 100, 
                        },
                })
```

But that eats my quota, even when there's nothing new. I want to send an `If-None-Match` header with my requests (using the `ETag` value from the `*github.Response.Response.Header`), which doesn't count towards my quota. But there isn't a clean way to do this now, outside of making a new `*github.Client` for each call with a custom `http.RoundTripper` to add the `If-None-Match` header, which is slightly gross.

Any thoughts on me adding a new field to `IssueListByRepoOptions` like `Cache *CacheOptions` which could contain `IfNoneMatch string` (with docs on how to set it) and `IfModifiedSince time.Time`?

/cc @willnorris @gmlewis @kevinburke

**Comment by bradfitz** [comment]
And /cc @shurcooL

**Comment by gmlewis** [comment]
SGTM!

**Comment by shurcooL** [comment]
> I currently do this in a loop ... But that eats my quota

@bradfitz Are you already using a caching HTTP transport?

Before I look into it further, just want to first ask if you've already seen/read this section:

https://godoc.org/github.com/google/go-github/github#hdr-Conditional_Requests

(It's also in README at https://github.com/google/go-github#conditional-requests.)

As far as I know, that's the recommended way to achieve client-side HTTP caching and making conditional requests that don't use use up rate limit quota unnecessarily.

For example, see https://github.com/shurcooL/home/blob/9c57e59a05baa9513b847fd945865935b7e529c2/users.go#L29-L33.

(Another [example of a small program](https://github.com/dinedal/message_droid/blob/d738c75ce2220ef163f978a94f5ea1934d136edf/services/github_closed_issues/main.go#L36-L41) that continuously polls for issues within an organization, and can run 24/7 without exceeding rate limit by making good use of `httpcache` package to support caching and therefore make conditional requests that don't use up quota. Disclaimer, that code is old and not actively used, so it might be slightly out of date.)

Or is there a reason this would be an exception?

**Comment by bradfitz** [comment]
Oh, no, I wasn't using github.com/gregjones/httpcache. Will try.

I searched the godoc page for "ETag" and "NoneMatch" and "None-Match" and didn't find those and then went to search the issue tracker.

**Comment by shurcooL** [comment]
> Oh, no, I wasn't using github.com/gregjones/httpcache. Will try.

Got it. I believe using it should fix the issue, let me know if not.

I'm a little surprised no one suggested this in this issue before. I'm not sure how I missed this issue myself, otherwise I would've commented earlier.

> I searched the godoc page for "ETag" and "NoneMatch" and "None-Match" and didn't find those and then went to search the issue tracker.

Thanks. Perhaps we should expand the package comment/README to include those keywords to make it easier for people to find. Additionally, there's `Last-Modified` and `If-Modified-Since`.

**Comment by shurcooL** [comment]
I found a relevant (closed) issue #412 where I did mention the expectation to use a caching `http.Transport`.

Although, @willnorris's last paragraph in https://github.com/google/go-github/issues/412#issuecomment-236231653 says:

> All that said, I don't think I've ever looked at #242 closely, so am not sure if we have all the right abstractions in place to be able to support what it's talking about.  I'll try to take look at that.

So maybe this issue is about something subtly different and perhaps more needs to be done for the original issue. Perhaps the original poster (/cc @bithavoc) can expand on whether using a caching `http.Transport` would work for them, since they haven't mentioned it so far, so I can't know.

**Comment by bradfitz** [comment]
@shurcooL, actually, github.com/gregjones/httpcache doesn't quite work for me. Its MemoryCache doesn't have any sort of LRU eviction or limits, and I hit lots of URLs, causing it to use too much memory.

There is a Delete method (https://github.com/gregjones/httpcache/blob/9c8ca9f/httpcache.go#L81) but there's no documentation about the key, nor ways to enumerate all the existing keys. 

If I'm going to have to create a new httpcache.Transport per request/type anyway, I might as well just go with my original hacky plan in https://github.com/google/go-github/issues/242#issuecomment-287190057

Or start hacking on httpcache, but I'm already a few dependencies away from the code I want to be writing. :-/

/cc @gregjones

**Comment by bradfitz** [comment]
(Well, I suppose I could just provide httpcache.Transport my own implementation of httpcache.Cache.)

**Comment by shurcooL** [comment]
> Its MemoryCache doesn't have any sort of LRU eviction or limits, and I hit lots of URLs, causing it to use too much memory.

I see.

I know there is one `httpcache.Cache` implementation that _sounds_ close to what you're describing. It's listed at https://github.com/gregjones/httpcache#cache-backends:

> [`github.com/die-net/lrucache`](https://github.com/die-net/lrucache) provides an in-memory cache that will evict least-recently used entries.

And, from its README:

> LruCache is a thread-safe, in-memory [httpcache.Cache](https://github.com/gregjones/httpcache) implementation that evicts the least recently used entries when a byte size limit or optional max age would be exceeded.

However, I've never used it myself and can't vouch for how well it works (or at all). Do you wanna give it a shot?

> (Well, I suppose I could just provide httpcache.Transport my own implementation of httpcache.Cache.)

Right, implementing your own `httpcache.Cache` is also an option, that package is meant to be pretty flexible.

**Comment by bradfitz** [comment]
Well, implementing my own works (https://go-review.googlesource.com/c/38163/11/maintner/github.go#798), but now I lose access to Github's "X-Poll-Interval" response header, since httpcache eats the 304 and gives me my old cached copy, with a missing or stale value of Github's "X-Poll-Interval" (adjusted by Github based on their load: https://developer.github.com/v3/activity/events/).

If I continue down the httpcache package route, it would need configuration for which headers from the 304 response to copy to the cached response.

**Comment by gregjones** [comment]
I think the response should technically have X-Poll-Interval in a Connection header, if it's something that shouldn't be taken from the cached response. A simple RoundTripper implementation that adds that "Connection: X-Poll-Interval" to the response before returning it would make `httpcache` play nice.

Having said that, adding config to override it sounds reasonable.

**Comment by m4ns0ur** [comment]
I used `httpcache` as recommended, but it's not working properly. Actually in the first time when it's creating the disk/leveldb cache, it works correctly, but after a while if you retry, it doesn't care about cache anymore.
I'm calling `github.GetContents`.
```
cache, err := leveldbcache.New("cache")
	if err != nil {
		log.Println("Could not setup the cache; fallback in default transport")
		cl = github.NewClient(nil)
	} else {
		cl = github.NewClient(&http.Client{Transport: httpcache.NewTransport(cache)})
	}
...
repContent, _, resp, err := cl.Repositories.GetContents(ctx, "foo", "bar", path, nil)
```

**Comment by gmlewis** [comment]
> If I continue down the httpcache package route, it would need configuration for which headers from the 304 response to copy to the cached response.

I'm closing this issue because many alternatives were discussed, but I think it would be beneficial if a new issue were opened with clearer specific guidance as to how to best solve the issue (if there is still interest, that is).

Alternatively, feel free to reopen this issue with more details as to what is needed to be done here.
