### ISSUE TITLE
ListAlertsForOrg options should support cursor pagination

### ISSUE THREAD

**Issue by jporzucek** [google/go-github#2511]
At the moment `ListAlertsForOrg` function supports only offset (`page`) pagination while querying REST API [https://api.github.com/orgs/ORG/code-scanning/alerts](https://api.github.com/orgs/ORG/code-scanning/alerts) endpoint returns `link` header with `after` query parameter. Therefore, the `AlertListOptions` struct should include `ListCursorOptions` field.

**Comment by gmlewis** [comment]
According to the docs here: https://docs.github.com/en/rest/code-scanning#list-code-scanning-alerts-for-an-organization
These endpoints also take a `page` parameter that it an integer, which is what `ListOptions` provides.

So unfortunately, this is not a simple replacement, and #2512 would be a breaking API change that would confuse anybody currently using the `Page` field.

This is going to need some discussion as how to correctly solve this situation.
My initial thought is that we need a third type of `ListCursorOptions` where `Page` is an `int` instead of a `string`, but am open to other ideas.

![ksnip_20221021-072251](https://user-images.githubusercontent.com/6598971/197185360-fcbcb3af-1239-46d6-9398-3f6f6ce9de6f.png)

**Comment by gmlewis** [comment]
Yikes! That is a bit disturbing, @jporzucek - thank you for the research!

Would you mind contacting GitHub tech support and explaining the situation to them and see if they have a recommendation for us here in this repo?  Feel free to point to this issue that you started.

**Comment by gmlewis** [comment]
> This seems to be a consistent issue across GitHub's API. I had just recently resolved this issue for Secret Scan Alerts #2446

Ah, right... thank you for the reminder, @AbbanMustafa !
So we are fine with pulling in both types of list options into the struct where it is necessary.

@jporzucek - could you please do something similar to #2446 ?
