### ISSUE TITLE
Change type of RunnerGroup.SelectedWorkflows to `*[]string`

### ISSUE THREAD

**Issue by bob-bins** [google/go-github#2570]
`go generate` does not generate `GetSelectedWorkflows` given the `[]string` type.

**Comment by gmlewis** [comment]
> `go generate` does not generate `GetSelectedWorkflows` given the `[]string` type.

That is correct, because a `[]string` does not need an accessor, as there is no possibility of a `nil` dereference.

There is no need that I'm aware of to change the field to type `*[]string` as that is only needed in very rare circumstances, and I don't think this is one of them, correct?  Why do you wish to change it?

**Comment by bob-bins** [comment]
Makes sense!

(I'm new to Golang projects, so I wasn't sure if there was a convention where it's preferred to access values through getter functions, but after some review following your comment it makes sense that there's no need for this)
