### ISSUE TITLE
Create Repo with Discussion Enabled

### ISSUE THREAD

**Issue by TruRelax** [google/go-github#2586]
According to the API doc: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28

```
has_discussions boolean
Whether discussions are enabled.
Default: false
```

A new field `has_discussions` is added to enable discussion, this SDK should support it as well.

**Comment by gmlewis** [comment]
Thanks, @TruRelax - are you interested in making a PR, or should this issue be opened up to other contributors to the repo?

**Comment by TruRelax** [comment]
@gmlewis Hope other contributors can fix this. Google's CLA is kinda hard for me to sign :-(

**Comment by gmlewis** [comment]
> @gmlewis Hope other contributors can fix this. Google's CLA is kinda hard for me to sign :-(

No worries, @TruRelax .

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by gronsy** [comment]
I'd like to work on this in case no one else wants it. I'd be contributing for the first time and this looks like a good issue to start on. I do have some commitments to do over these day on two, but should squeeze some time to work on it.

**Comment by gmlewis** [comment]
> I'd like to work on this in case no one else wants it. I'd be contributing for the first time and this looks like a good issue to start on. I do have some commitments to do over these day on two, but should squeeze some time to work on it.

Thank you, @gronsy !  It's yours.
