### ISSUE TITLE
Add new machine types to response of GetWorkflowRunUsageByID

### ISSUE THREAD

**Issue by tragiclifestories** [google/go-github#2595]
Hi! As we're all probably aware, Github has added a bumch of different machine sizes to the actions runners. The timings endpoint returns these under keys like `UBUNTU_4_CORE`, etc. But the present version of this package only supports the 'vanilla' `WINDOWS`, `MACOS` and `UBUNTU` runners. It would be helpful to add the others if possible. Would obviously be a breaking change - not sure what the process is for handling that but happy to throw a PR together if someone can point me to all that.

**Comment by gmlewis** [comment]
Thank you, @tragiclifestories !

I'm now wondering if instead of [hard-coding these billing environments](https://github.com/google/go-github/blob/master/github/actions_workflow_runs.go#L66-L77) like we do now, we should instead make a flexible map where we don't restrict the key names, since GitHub at any time could add a new type of billing environment.  In fact, their [current documentation](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#get-workflow-run-usage) doesn't even mention the one you are showing, so this is very likely the case.

So instead of this:

```go
// WorkflowRunUsage represents a usage of a specific workflow run.
type WorkflowRunUsage struct {
	Billable      *WorkflowRunEnvironment `json:"billable,omitempty"`
	RunDurationMS *int64                  `json:"run_duration_ms,omitempty"`
}

// WorkflowRunEnvironment represents different runner environments available for a workflow run.
type WorkflowRunEnvironment struct {
	Ubuntu  *WorkflowRunBill `json:"UBUNTU,omitempty"`
	MacOS   *WorkflowRunBill `json:"MACOS,omitempty"`
	Windows *WorkflowRunBill `json:"WINDOWS,omitempty"`
}
```

maybe this would make more sense?


```go
// WorkflowRunUsage represents a usage of a specific workflow run.
type WorkflowRunUsage struct {
	Billable      map[string]*WorkflowRunBill `json:"billable,omitempty"`
	RunDurationMS *int64                  `json:"run_duration_ms,omitempty"`
}
```

Thoughts?

**Comment by tragiclifestories** [comment]
I think that's probably the way to go - surely only a matter of time before there's GPU machines and all sorts. 

Of course, that becomes an even bigger API change for existing users ...
