### ISSUE TITLE
Deployment Branch Policies is not implemented

### ISSUE THREAD

**Issue by srikrsna-buf** [google/go-github#2610]
Deployment branch policies endpoints are not implemented. Docs: https://docs.github.com/en/rest/deployments/branch-policies?apiVersion=2022-11-28.

I want to implement this and any guidance on where this should end up? I am guessing under `Actions` as that is the required permission to access this

**Comment by gmlewis** [comment]
How about adding this support to the end of [github/repos_environments.go](https://github.com/google/go-github/blob/master/github/repos_environments.go) ?

**Comment by Ismael-Moreno** [comment]
Hi, I coded an implementation for the deployment branch policies endpoint. Check the PR for the case it helps in this issue: #2621

**Comment by gmlewis** [comment]
Thanks, @Ismael-Moreno , but before we review your PR, let's please first find out if @srikrsna-buf has a PR that is almost ready to review since this issue was assigned to @srikrsna-buf . If so, we will move forward with that one.
If not, then it is @srikrsna-buf 's call as to whether to move forward or not with your PR.

**Comment by srikrsna-buf** [comment]
I don't have one yet. @Ismael-Moreno Thank you for the PR.

**Comment by gmlewis** [comment]
Thanks, @srikrsna-buf - re-assigning to @Ismael-Moreno and continuing with PR.
