### ISSUE TITLE
Add support for configuration variables in workflows

### ISSUE THREAD

**Issue by jwenz723** [google/go-github#2624]
Recently GitHub added support for configuration variables in github actions workflows: https://github.blog/changelog/2023-01-10-github-actions-support-for-configuration-variables-in-workflows/

Please add support for creating configuration variables. Configuration variables can be created at the organization, repository, or environment level so support for all 3 of these scopes should be added.

**Comment by gmlewis** [comment]
I'm having difficulties finding the GitHub v3 API documentation from that blog post that describes these features.
Can you please point me to the docs for the GitHub v3 API that manipulates these configuration variables?

If it turns out there isn't one, then this repo will be unable to do what you've requested, since this is a Go client library whose sole purpose is to make it easy to call the GitHub v3 RESTful API from Go. If the API can't do something, this client library can't do it either.

Thanks.

**Comment by janslow** [comment]
I believe its [these API docs](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28#get-a-repository-variable)

**Comment by gmlewis** [comment]
Ah, thank you, @janslow !  I'll open this up to any contributor to the repo (unless you want to write a PR).

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by michiboo** [comment]
@gmlewis  hello I would like to try this issue if it is not WIP

**Comment by gmlewis** [comment]
> @gmlewis hello I would like to try this issue if it is not WIP

Thank you, @michiboo !  It's yours.

**Comment by michiboo** [comment]
@gmlewis  after I read the doc of github action variable, I am abit confuse, do I need to fetch the repository variable using the API or I need to add it to my fork and replace the non-sensitive variable in the workflow file?

**Comment by gmlewis** [comment]
> @gmlewis after I read the doc of github action variable, I am abit confuse, do I need to fetch the repository variable using the API or I need to add it to my fork and replace the non-sensitive variable in the workflow file?

@michiboo - we need a new pair of Go files in our repo:
* `github/actions_variables.go`
* `github/actions_variables_test.go`

that implement all of the endpoints listed on this web page: https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28

I've highlighted all the endpoints we need by drawing a red box around them on the left-hand side.

![ksnip_20230113-164212](https://user-images.githubusercontent.com/6598971/212425136-e5db2117-44ab-469b-b173-8897da541695.png)

If this is more work than you planned on volunteering for, no problem... just say the word and we can remove your name from this issue and open it up to other contributors who would like to work on it. Either way is totally fine.

Thank you, @michiboo !

**Comment by michiboo** [comment]
@gmlewis  no problem I think i can do it, it doesn't look too difficulty in term of technicality

**Comment by stockmaj** [comment]
Any update on this?  Do you have an ETA?

**Comment by michiboo** [comment]
Hi I nearly implemented all the API, and still need to test it, I think it
should be ready early next week, if it's urgent I can upload the work I did
and then someone can take over
