### ISSUE TITLE
[DevExperience]: Inconsistency in time related field types

### ISSUE THREAD

**Issue by zombieleet** [google/go-github#2645]
I am currently working with `go-github` sdk, and I noticed some inconsistencies in the types of time fields. Some fields are `*time.Time` while others are `*Timestamp`.

For example, this difference can be spotted in the [PullRequest](https://pkg.go.dev/github.com/google/go-github/v49/github#PullRequest) and [Projects](https://pkg.go.dev/github.com/google/go-github/v49/github#Project) struct. It is also littered around the codebase. In my opinion, let's stick to one type for time fields which is `*Timestamp`.

if this is seen as a valid issue, I will open a PR to fix it. 

Thanks.

**Comment by gmlewis** [comment]
Thank you, @zombieleet .
It seems like there was a discussion about this before, but I'm not finding it.

Consistency would be nice, and I can't think of any downsides other than a boat-load of breaking API changes.
But that's why we version this, and people can hold back until they feel like upgrading.

So I have no objections to a PR.

**Comment by gmlewis** [comment]
Fixed by: https://github.com/google/go-github/pull/2646
Closing.
