### ISSUE TITLE
Add Permission filter to collaborators list

### ISSUE THREAD

**Issue by MytsYurii** [google/go-github#2651]
in official documentation here: https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28
there is a possibility to add "permission" parameter.

It allows to filter collaborators by the permissions they have on the repository. If not specified, all collaborators will be returned.

Can be one of: pull, triage, push, maintain, admin

Can you add this filter to ListCollaborators endpoint, to ListCollaboratorsOptions struct?

**Comment by gmlewis** [comment]
Thank you, @MytsYurii !

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by Sairaviteja27** [comment]
@gmlewis Hi, I would like to work on this issue

**Comment by gmlewis** [comment]
> @gmlewis Hi, I would like to work on this issue

Thank you, @Sairaviteja27 !  It is yours.

**Comment by MytsYurii** [comment]
Great, Thank you @gmlewis and @Sairaviteja27!
