### ISSUE TITLE
Set authenticated user's email visibility via API

### ISSUE THREAD

**Issue by aaront97** [google/go-github#2688]
Hi, 

I want to set the authenticated user's email visibility to public. There is a way to do this according to the docs, https://docs.github.com/en/rest/users/emails?apiVersion=2022-11-28#set-primary-email-visibility-for-the-authenticated-user, but seems the library is missing this. Can we add this, please?

**Comment by gmlewis** [comment]
Thank you, @aaront97 !

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by gmlewis** [comment]
> Hi @gmlewis , I can work on this

Thank you, @Sairaviteja27 !  It's yours.

**Comment by v4rn** [comment]
hi @Sairaviteja27 if you haven't had the chance to look at this, can I take this one?

**Comment by Sairaviteja27** [comment]
Hi @v4rn, I am currently working on this, thanks.
