### ISSUE TITLE
Support enumerating the known event types

### ISSUE THREAD

**Issue by evankanderson** [google/go-github#2863]
It looks like `go-github` has [an internal list of all the GitHub event types ](https://github.com/google/go-github/blob/899235e0a9d750d6fecf9048a676046d50f9d4a3/github/messages.go#L46).  I'd like to be able to iterate over the list in my own code where I route events based on event type.  I'm thinking of exposing the following methods:

```golang
// WebhookTypes returns a list of all the known GitHub event type strings supported by go-github.
func WebhookTypes() []string {
  // ...
}

// EventForType returns an empty struct matching the specified GitHub event type.
func EventForType(messageType string) any {

}
```

The second method would extract a lot of `Event.ParsePayload` https://github.com/google/go-github/blob/master/github/event.go#L30, so it wouldn't be much additional code.

**Comment by gmlewis** [comment]
I have no problem with that as long as you can refactor to reuse existing code as much as possible.
I say this because any time a new PR comes in to support a new webhook event type, it is a bit of a pain to make sure you tweak all the various places that need tweaking, and it would be nice to not add more pain to this process.
