### ISSUE TITLE
WebHookPayload incorrectly defines repo/organization

### ISSUE THREAD

**Issue by aleemstreak** [google/go-github#302]
I'm trying to use the WebHookPayload struct to deserialize a webhook received by my server from Github. 

The WebHookPayload is mostly defined correctly, however, it includes a Repo field of type Repository. Repository has a field name organization of type Organization. 

However, when receiving webhooks for push events, this organization field is actually sent as a string id by github, not the nested Organization object. 

This cases decoding json of a webhook to a WebHookPayload to fail. I'd like to contribute a fix however, I'm looking for suggestions on the best way to do this. Since the Repository struct is used all over the place, can't really change that struct. The only thing I can think of is to create a WebHookRepository struct that is 99% the same except for the organization field.

Any other ideas?

**Comment by willnorris** [comment]
Try using `PushEvent`, which had a `PushEventRepository` that handles this discrepancy.  I guess I hadn't realized that `PushEvent` and `WebHookPayload` are effectively duplicates.  I don't remember why that is (I'll have to look through the commit history), but I suspect we'll deprecate `WebHookPayload` in favor of `PushEvent`.

**Comment by aleemstreak** [comment]
Thanks for the quick response. 

Unfortunately, I think PushEvent is a little out of date as well. Specifically, it uses PushEventCommit which doesn't correctly parse the commit sha. It uses a property name called "SHA" instead of "id" that I see in the json of the webhook payload.

I think it might make sense to use the standard []Commit instead of []PushEventCommit.

I discovered a few other inconsistencies as well and I'm happy to enumerate them all but just want to make sure this is on the right path first...

**Comment by willnorris** [comment]
yeah, @gmlewis and I were just looking at the SHA versus ID thing as well.  GitHub's own documentation (https://developer.github.com/v3/activity/events/types/#pushevent) on this is inconsistent.  The table says "sha", but the example payload directly below it says "id".  In our testing, it seems like the "id" is correct, so that should be updated in the `PushEvent` type.

As for `[]Commit` versus `[]PushEventCommit`, I do think we need the extra fields that PushEventCommit has, but I'd certainly be curious to hear your thinking.  And yeah, go ahead and point out any other inconsistencies you've noticed.  We're really just starting to use these different webhook event types much more heavily at Google, so now's a good time to focus on cleaning them up.

**Comment by gmlewis** [comment]
Keeping open as this is closely related to https://github.com/google/go-github/issues/303#issuecomment-894413530 .

**Comment by gmlewis** [comment]
`PushEventCommit` was changed to `HeadCommit` in #1449 and `PushEvent` uses `HeadCommit` so I believe this issue can be safely closed in deference to the remaining issue #303.
