### ISSUE TITLE
Deprecate WebHookPayload

### ISSUE THREAD

**Issue by willnorris** [google/go-github#303]
The `PushEvent` type was originally added in June 2013 in beaff13913b3dd17651e12f622473b1fb99756a1.  I then added the `WebHookPayload` type a month later in 023e8db8cbba83d90a62e2e546a96d3dcecbbce4.  I honestly am not sure why I did that, since they are effectively duplicates.  Maybe it wasn't clear at that point that we should be using the same types for webhook payloads and activity events?  Or maybe I just wasn't thinking.

In any event, #302 reminded me that we've updated `PushEvent` to include a variant of `Repository` that has a string Organization filed (see d722750ab19bf6318a2c8dfad8d4aa034779aa8f), but the same update was never made to `WebHookPayload`.  Instead of fixing that, I think we should probably just deprecate `WebHookPayload` and point people to `PushEvent` instead.

**Comment by parkr** [comment]
> I think we should probably just deprecate WebHookPayload and point people to PushEvent instead.

Agreed. I'm happy to submit a patch for this. How would you go about deprecating this? Just a comment? Or do you mean to remove this struct? Or alias it, e.g. `type WebHookPayload PushEvent`?

**Comment by willnorris** [comment]
I was originally just thinking about a comment, but I suspect that aliasing the type should work fine as well.  I can't imagine that anyone is actually unmarshalling a push event they've received from GitHub into a `WebHookPayload` because of #131.  

(somewhat ironically, which I just noticed today, #131 is reporting an issue on WebHookPayload, but the commit that fixed it d722750 was patching PushEvent, so the originally reported issue was technically never addresses)

**Comment by RobbieMcKinstry** [comment]
Hi, all!
This may be tangential to this issue, but it's at least somewhat related:
since this repo doesn't release tags, deprecating and removing this method is probably a breaking change for someone out there. Like @willnorris said, it's unlikely, but still technically a breaking change if you guys decide to remove it.

I was wondering if there's a plan to mark to version this lib.

Sorry if I'm clouding the wrong channel with this comment. :)

**Comment by shurcooL** [comment]
@RobbieMcKinstry We have a discussion about that in #376.

**Comment by RobbieMcKinstry** [comment]
Thanks! I hadn't seen that issue!

**Comment by gmlewis** [comment]
It looks to me like this is still an issue, but may break existing users of the repo even with type aliases (due to the field mismatches).

So I'll leave the issue open and may attempt it myself depending on my workload... but for now I'll just leave the issue open in case anyone else wishes to address it.

**Comment by gmlewis** [comment]
> It looks to me like this is still an issue, but may break existing users of the repo even with type aliases (due to the field mismatches).

It turns out that simple deprecation here should work beautifully.  Opening PR to resolve.
