### ISSUE TITLE
Add support for  Actions list jobs for a workflow run attempt

### ISSUE THREAD

**Issue by fchimpan** [google/go-github#3059]
I am reaching out to inquire about support for the API. It appears that the API for `list jobs for a workflow run attempt` has not been implemented yet. I was wondering if it would be possible to consider adding this feature. docs: https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#list-jobs-for-a-workflow-run-attempt

Thank you very much for your attention and assistance. I look forward to any updates you might have on this matter.

**Comment by gmlewis** [comment]
Thank you, @fchimpan !

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by fchimpan** [comment]
@gmlewis 

Thank you for your reply.

I appreciate your guidance in pointing me to the documentation. I am interested in working on adding this feature.
Thanks again for your support and help.

**Comment by gmlewis** [comment]
Excellent, @fchimpan !  I wasn't sure you wanted to, but this is great news.  It's yours.
