### ISSUE TITLE
Merge Queues break repository ruleset unmarshaling

### ISSUE THREAD

**Issue by siddharthab** [google/go-github#3098]
In the [unmarshaling code](https://github.com/google/go-github/blob/2c1b36c92f356f33521a5433477e5eae3f9e94a7/github/repos_rules.go#L207), there is no case for `merge_queue`, and so the unmarshaling says that the rule type is not supported and errors out ([full list of possible types from GitHub](https://docs.github.com/en/graphql/reference/enums#repositoryruletype)).

Also, the error message has the wrong format verb, it should be `%q` or `%s` instead of `%T`.

To reproduce, create a ruleset with merge queues set, and try to get it using go-github.

**Comment by gmlewis** [comment]
Do you want to write a PR for this, @siddharthab , or should I open this up to other contributors to this repo?

**Comment by siddharthab** [comment]
Because I am new to the repo, it may take me longer to make a proper well tested change. Best to have more familiar people do it. Thanks for the quick reply!

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by Matthew-Reidy** [comment]
Hello, I am new to open source and would like to have a crack at this though I wont be able to work on it until the weekend.

**Comment by gmlewis** [comment]
> Hello, I am new to open source and would like to have a crack at this though I wont be able to work on it until the weekend.

Awesome!  Thank you, @Matthew-Reidy !  We appreciate your contributions in advance!
It's yours.

**Comment by Matthew-Reidy** [comment]
Hello, I began working on this yesterday but cant seem to find what parameters are required for merge_queue. Does anyone know this info? Im finding conflicting documentation. Thanks

**Comment by Matthew-Reidy** [comment]
Ah never-mind. I found the documentation. Looks like Merge_Queue rule does not require parameters.

**Comment by Matthew-Reidy** [comment]
Submitted my PR for the changes requested here.
