### ISSUE TITLE
Changing custom properties

### ISSUE THREAD

**Issue by R4vio** [google/go-github#3101]
The current library has only the possibility to GET custom properties, while the API has to option to also PATCH as can be seen here:
https://docs.github.com/en/rest/repos/custom-properties?apiVersion=2022-11-28#create-or-update-custom-property-values-for-a-repository

It would be nice if this feature would be included in the library

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by HariCharan-001** [comment]
I'd like to work on this.

**Comment by gmlewis** [comment]
> I'd like to work on this.

Thank you, @HariCharan-001 !   It's yours.

**Comment by HariCharan-001** [comment]
Submitted a PR, please review !

**Comment by HariCharan-001** [comment]
Raised a new PR !

**Comment by bhanurp** [comment]
this looks to addressed in #3109

**Comment by gmlewis** [comment]
> this looks to addressed in #3109

Thank you, @bhanurp !
Closing as completed.
