### ISSUE TITLE
LIst of issue comments do not collect the comment which was added during the creation of the PR.

### ISSUE THREAD

**Issue by MytsYurii** [google/go-github#3126]
<img width="949" alt="Screenshot 2024-04-09 at 14 03 16" src="https://github.com/google/go-github/assets/101092494/64f44a3a-a186-4add-ad10-88cf351db960">

Im using the Github API to collect the list of issue comments: 
repos/%v/%v/issues/%d/comments
for some reason this API do not return me a comment which was added during the PR creation procedure and return only the list of comments which I added after the PR creation.

Can someone fix it ?

**Comment by MytsYurii** [comment]
@gmlewis @jwhett @willnorris  i will be very pleasure if you can check this issue soon.

**Comment by MytsYurii** [comment]
here is a documentation link: https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#list-issue-comments

**Comment by MytsYurii** [comment]
> @MytsYurii - I don't mind if you tag me ( @gmlewis ), but please do not tag others to look at an issue unless you have a really good reason. Thanks.
sorry for that, but looks like the API is working not as expected, and I've tested it with the postman - same issue.

**Comment by willnorris** [comment]
Even though GitHub renders them very similarly, the first "comment" on an issue is the issue body itself, not actually a comment.  GitHub doesn't include that in the comments endpoint you mentioned.  Instead you need to call the endpoint to fetch the issue object.  For example, for this issue here, here are the comments:

https://api.github.com/repos/google/go-github/issues/3126/comments

Note how they do not include your original post.  That can be found when on the `body` field of the issue object: https://api.github.com/repos/google/go-github/issues/3126  (the go-github equivalent would be `client.Issues.Get` I think)

This is just the behavior of the GitHub API, and not anything to do with this client library.

**Comment by MytsYurii** [comment]
Thanks a lot!
