### ISSUE TITLE
Can't remove  repository ruleset's every Bypass Actors because of serialization issue

### ISSUE THREAD

**Issue by lado936** [google/go-github#3137]
Hello all, 
I am using go-github repository ruleset update function from [here](https://github.com/google/go-github/blob/8d4be0b2cf2b8242a0b7e3777232cd0058ae535f/github/repos_rules.go#L493)

but issue is that, if i already have bypassactors set and want to remove all of them, it not applying changes as bypassactors has omitempty set [here](https://github.com/google/go-github/blob/8d4be0b2cf2b8242a0b7e3777232cd0058ae535f/github/repos_rules.go#L391), if i understand correctly, omitempty must be removed if i want to pass empty list there. Proposing to remove omitempty if there is no case i can't see, why its needed.

**Comment by lado936** [comment]
Better, if someone else will work on this, new to Golang and will need way more time i guess

**Comment by gmlewis** [comment]
> Better if someone else will work on this, new to Golang and will need way more time i guess

OK, no problem.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by Matthew-Reidy** [comment]
I can take this
