### ISSUE TITLE
Space being stripped from Workflow Run, Job, and Step Names

### ISSUE THREAD

**Issue by jb-2020** [google/go-github#3190]
Hey folks, looking for clarification: 

The following truncated event: 
```
{
    "workflow_job": {
      ...
      "name": "GitHub Actions Test",
      ....
}
 ```

`event.WorkflowJob.GetName()`  results in `GitHubActionsTest`.  It appears _something_ in this library is stripping all the space from these names.  Behavior observed in v61 and v62.  Any insight here?

**Comment by gmlewis** [comment]
To debug these types of things, I frequently like to take advantage of https://github.com/gmlewis/go-httpdebug
so that I can see what the exact `curl` equivalent is of the call that I'm making...

Often, issues like this end up being caused by the GitHub v3 API being sensitive to HTTP header values.

If you could test this out and report back, it would be greatly appreciated.

**Comment by jb-2020** [comment]
Ah, thanks @gmlewis your comment kicked me in the right direction.  It wasn't the headers but a bug in our testing script. Apologies!

**Comment by gmlewis** [comment]
> Ah, thanks @gmlewis your comment kicked me in the right direction. It wasn't the headers but a bug in our testing script. Apologies!

No worries!  Glad you found the issue.
