### ISSUE TITLE
Sorting Not Supported

### ISSUE THREAD

**Issue by Kedarnag13** [google/go-github#321]
This library has helped me immensely, however I am making use of "ListByOrg" to list all the repositories. But since my organization has a lot of them, and to show them all would not be suitable for me. It would be nice if "RepositoryListByOrgOptions" could provide Sort option with values similar to others such as "updated" and "created".

Regards.

**Comment by willnorris** [comment]
In most cases, go-github tries to be a pretty strict client of the [GitHub API](https://developer.github.com/v3/).  The API doesn't actually support that kind of sorting (as far as I know), so that's why go-github doesn't either.  It wouldn't be too hard to write a simple type that implements sort.Interface that allows sorting on whatever field you want.  But that kind of thing is out of scope for the library itself.

**Comment by willnorris** [comment]
Closing this issue for now.  If the GitHub API does actually add support for this kind of sorting, feel free to reopen.

**Comment by Xopherus** [comment]
@willnorris it looks like this is supported by the v3 API now, can this be reopened?

See https://developer.github.com/v3/repos/#list-organization-repositories

**Comment by gmlewis** [comment]
Since #1257 has been opened, leaving this issue closed.
