### ISSUE TITLE
Implementing Personal Access Tokens API

### ISSUE THREAD

**Issue by AbhishekAg** [google/go-github#3213]
I want to use personal token api, but the go implementation is missing in the go-github package.
Please help to implement the same and commit in the main repo, so that I can pull the latest codebase and use it.

Github Rest API doc:
https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/personal-access-tokens?apiVersion=2022-11-28#list-fine-grained-personal-access-tokens-with-access-to-organization-resources

Below CURL command is working and able to list the fined grained access tokens authorised by the organization

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/orgs/ORG/personal-access-tokens
```

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by arymoraes** [comment]
Can I take this?

I had lots of fun on the previous issue.

**Comment by gmlewis** [comment]
Absolutely, @arymoraes, and thank you! 
It's yours.

**Comment by arymoraes** [comment]
> Absolutely, @arymoraes, and thank you! It's yours.

Awesome! Thank you again.

**Comment by AbhishekAg** [comment]
@arymoraes Will PR take sometime?
