### ISSUE TITLE
Wrong parameter parsing in Link header for client.Users.ListAll()

### ISSUE THREAD

**Issue by vetinari** [google/go-github#326]
The call to
```go
users, res, err := client.Users.ListAll(&github.UserListOptions{1})
```
always returns `res.NextPage == 0`. This call uses the `since` parameter in the `Link:` header and not the `page` parameter like all others, see https://developer.github.com/v3/users/#get-all-users.

**Comment by willnorris** [comment]
For Users.ListAll and similar methods, pagination should be done by setting the `UserListOptions.Since` field to the last ID value seen.  resp.NextPage doesn't work for those methods (as you've discovered).
This is discussed a bit on #278.

I think the best fix for this is to just add an example for these methods that demonstrate how to do pagination.

**Comment by vetinari** [comment]
Figured that out... for reference:
```go
    var allUsers []github.User
    var users []github.User
    opt := &github.UserListOptions{Since: 0}
    for {
        users, _, err = client.Users.ListAll(opt)
        if err != nil {
            break
        }
        if len(users) == 0 {
            break
        }
        allUsers = append(allUsers, users...)
        opt.Since = *(users[len(users)-1]).ID
    }
    if err != nil {
        log.Fatalf("Failed to fetch users: %s\n", err)
    }

```
