### ISSUE TITLE
Feature: repository ruleset event type not defined

### ISSUE THREAD

**Issue by rbtcollins** [google/go-github#3295]
From https://github.com/cbrgm/githubevents/issues/94#issuecomment-2378597876 - GitHub are now creating repository rulesets by default rather than branch protection rules (via the UI at least).

[API definition](https://docs.github.com/en/webhooks/webhook-events-and-payloads#repository_ruleset).

**Comment by gmlewis** [comment]
Would you like to create a PR for this, @rbtcollins , or shall I open this up to other contributors to this repo?

**Comment by rbtcollins** [comment]
I don't think I have an active google CLA with my current employer, and last time I discussed such with legal we got stuck. So I'm not sure I can commit to a PR.

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by gmlewis** [comment]
> Hi @gmlewis @rbtcollins I'd like to work on this

Thank you, @unamdev0 !
It's yours.

**Comment by unamdev0** [comment]
Hi @gmlewis, one small doubt, if you check the properties of `repository_ruleset` object [here](https://docs.github.com/en/webhooks/webhook-events-and-payloads#repository_ruleset), there's a `condition` key which is given as object or null, but what'll be the keys for this object are not given.

What should be done in this case? should I declare it as `map[string]interface{}` field as to accommodate anything that comes inside `condition` object

**Comment by unamdev0** [comment]
Cool, will use this
