### ISSUE TITLE
Propagate *http.Response when encountering a *url.Error?

### ISSUE THREAD

**Issue by akshayravikumar** [google/go-github#3362]
Why does [this code](https://github.com/google/go-github/blame/master/github/github.go#L853-L861) return nil for the response? I'm getting 404 errors (which can be permissions errors) but I'm not finding a good way to programmatically get the status code directly from the error object.

**Comment by gmlewis** [comment]
That's a good point. I don't see why we couldn't modify this endpoint to return the response so that the status code can be checked.

@akshayravikumar - do you want to write a PR to fix this, or shall I open this issue up to other contributors?

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.
Also feel free to perform a code review on any PR that has the label "NeedsReview" - we appreciate those contributions too!

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by silasalberti** [comment]
Hey I'm a new contributor and thought this issue looked like a good start. Just submitted this: #3369
