### ISSUE TITLE
Remove projects as the REST API for these is no longer available

### ISSUE THREAD

**Issue by stevehipwell** [google/go-github#3367]
The projects (classic) [REST API](https://docs.github.com/en/rest/projects/projects?apiVersion=2022-11-28) has been [removed](https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/) so this should also be removed from here.

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.
Also feel free to perform a code review on any PR that has the label "NeedsReview" - we appreciate those contributions too!

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by stevehipwell** [comment]
@gmlewis I think this issue requires attention from one of the maintainers as projects are integrated across more than just the projects service. I attempted a quick removal and came across a lot of issues to resolve, I suspect that there is more broken functionality that just the project service erroring.

**Comment by gmlewis** [comment]
@stevehipwell - when you have time, a code review of #3380 would be greatly appreciated.
