### ISSUE TITLE
Mark teams functionality that's based on ID as deprecated

### ISSUE THREAD

**Issue by stevehipwell** [google/go-github#3368]
The teams functions that use ID should be deprecated as the REST APIs have been marked a legacy and are under a closing down notice ([ref](https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#get-a-team-legacy)).

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.
Also feel free to perform a code review on any PR that has the label "NeedsReview" - we appreciate those contributions too!

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!
