### ISSUE TITLE
Support for custom header values on requests

### ISSUE THREAD

**Issue by jrbasso** [google/go-github#412]
GitHub's API define few headers that can be passed to the methods, such as `If-None-Match`, `If-Modified-Since`, `Time-Zone`. The first 2 would generate a 304 response and the last one is just informative for adding content. All defined on https://developer.github.com/v3/.

The first 2 helps specially for who is having problems with the rate limit and just revalidating some content since the 304 responses doesn't consume a request. I was trying to think on how it could be implemented since it's not an error, but also not the full structure. What do you guys think in making the Response with the regular information, error and expected struct from the request be nil? To set the etag/last modified would probably live in the `Client` and cleared after every request.

`Time-Zone` could be set in the `Client`.

Implementing this would help the #242

**Comment by shurcooL** [comment]
> The first 2 helps specially for who is having problems with the rate limit and just revalidating some content since the 304 responses doesn't consume a request.

About the first 2 headers, they are usually taken advantage of by using a caching HTTP transport with go-github. See https://github.com/google/go-github#conditional-requests. Are you already familiar with that?

**Comment by jrbasso** [comment]
Got it. I thought it would be the workaround, but having these headers in the lib would be nice. It is not necessarily a caching. The requests could be days apart if you store the etag/last modified value.

But I understand if that's not approved to be part of this repo.

**Comment by willnorris** [comment]
The general philosophy we've tried to take is that go-github should only be responsible for things that are specific to the GitHub API.  This is why the library itself knows nothing about caching, like @shurcooL said.  In general, it also knows nothing about authentication; we rely on standard go oauth libraries to handle that.  The exception here is the actual Authorization API endpoints, since that is GitHub specific, as well as the BasicAuthTransport since it also has a little GitHub specific logic for handling two-factor auth.

The corollary to this though, is that while go-github should not be handling things that are not specific to GitHub, it also shouldn't prevent you from hooking it up with other code that does do those things.  For example, the reason NewClient takes an http.Client rather than just using http.DefaultClient is precisely so that you can provide a client that does caching, authentication, etc.  You'll also note that most methods which implement API calls are generally very simple and follow a consistent pattern.  Most of the interesting logic is wrapped up in client.NewRequest and client.Do.  This also is intentional so that if you need to do anything out of the ordinary (like add additional headers to the request), you can call these methods directly.  And similarly, the response object we use provides some custom GitHub logic, but also exposes the underlying http.Response, so you can pull any response headers off of there that you want to access.

All that said, I don't think I've ever looked at #242 closely, so am not sure if we have all the right abstractions in place to be able to support what it's talking about.  I'll try to take look at that.

**Comment by jrbasso** [comment]
Thanks for the explanation. That makes totally sense.
