### ISSUE TITLE
Error code in README

### ISSUE THREAD

**Issue by headwindfly** [google/go-github#420]
I found a error in the following code(README.md):
```
client := github.NewClient(nil)

// list recently updated repositories for org "github"
opt := &github.RepositoryListByOrgOptions{Sort: "updated"}
repos, _, err := client.Repositories.ListByOrg("github", opt)
```
RepositoryListByOrgOptions has no member named `Sort`,  RepositoryListOptions?

**Comment by shurcooL** [comment]
Thanks for reporting this issue @headwindfly. You're absolutely right.

We should correct the example so it contains valid code.

There are many ways to fix it. One simple way I can think of is to change it to use an existing field of [`github.RepositoryListByOrgOptions`](https://godoc.org/github.com/google/go-github/github#RepositoryListByOrgOptions), such as `Type`. For example:

```Go
client := github.NewClient(nil)

// list member repositories for org "github"
opt := &github.RepositoryListByOrgOptions{Type: "member"}
repos, _, err := client.Repositories.ListByOrg("github", opt)
```

You've already contributed by reporting the issue, so thanks! If you want, you could also make a PR that fixes it.

If so, keep in mind that this will need to be updated in two files. The README.md file, as well as [github/doc.go](https://github.com/google/go-github/blob/b9698164669e386680621e2006cab02271257611/github/doc.go#L23-L27).

We want to keep those files in sync since they contain the same information. You can read issue #397 for more background information on that.

**Comment by headwindfly** [comment]
You are welcome. :)

But i do not want to make a PR, because I am fresh to this package, I don't know how to fix it, So...

**Comment by chandresh-pancholi** [comment]
@headwindfly  @shurcooL  I can pick this up if you guys allow.

**Comment by headwindfly** [comment]
@chandresh-pancholi ok :+1:

**Comment by chandresh-pancholi** [comment]
PR Raised. Please review and merge.
