### ISSUE TITLE
Discuss Pull Request Merge (squash) API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#457]
From #446 we are discussing the Preview API:
https://developer.github.com/changes/2016-04-01-squash-api-preview/
https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

The question is, do we have this (option 1):

``` go
opts := &github.PullRequestOptions{
    CommitTitle: "My commit",
    MergeMethod: "squash",
}
_, _, err := client.PullRequests.Merge(owner, repo, number, commitMessage, opts)
```

or (option 2):

``` go
opts := &github.PullRequestOptions{
    CommitTitle: "My commit",
    Squash: true,
}
_, _, err := client.PullRequests.Merge(owner, repo, number, commitMessage, opts)
```

Now that I write it that way, we would have to have separate `bool`s for each type of merge method (`merge`, `rebase`, etc.).

I vote for option 1.

Comments, thoughts?

**Comment by shurcooL** [comment]
This is what GitHub API presents, right?

Name | Type | Description
------|-------|------------
commit_title | string |Title for the automatic commit message.
commit_message | string | Extra detail to append to automatic commit message.
sha | string | SHA that pull request head must match to allow merge.
merge_method | string | Merge method to use. Possible values are merge, squash or rebase. Default is merge.

If so, I see no reason to deviate from that. This looks good to me:

```Go
github.PullRequestOptions{
	CommitTitle: "My commit",
	MergeMethod: "squash",
}
```

One thought. Using a freeform string for `MergeMethod` is pretty unpleasant, but viable if it's well documented. Its documentation absolutely must list explicitly the allowed values. Otherwise it's hard to know what they are, if case matters, etc.

Something to consider is an enum pattern, so that named constants can be used instead. I don't know if it's worth doing this here (we don't do it elsewhere in similar situations), but just a thought. It'd look a little like this:

```Go
type PullRequestOptions {
	...
	MergeMethod MergeMethod // Default is merge.
}

type MergeMethod string

const (
	Merge  MergeMethod = "merge"
	Squash MergeMethod = "squash"
	Rebase MergeMethod = "rebase"
)
```

And usage:

```Go
github.PullRequestOptions{
	CommitTitle: "My commit",
	MergeMethod: github.Squash,
}
```

**Comment by gsquire** [comment]
My vote is for option one as well. With regards to the string value for the merge method, I added documentation for what the valid options are thanks to CR by @gmlewis.

They are also listed in the documentation for the API. For a case with only three options, it seems like a string is OK.

**Comment by gmlewis** [comment]
I like the `MergeMethod` proposed by @shurcooL but as he said, we don't do it elsewhere in similar situations, so I'm thinking we should just leave it out.

I'm going to go ahead and close this issue and let's continue with option 1 in #446.

Feel free to reopen if anyone has any other ideas/comments.
