### ISSUE TITLE
Make empty responses due to 202 Accepted status code more visible.

### ISSUE THREAD

**Issue by caarlos0** [google/go-github#486]
I've built a tool to gather all stats of all repos in a given org and rank the users, and, as I just found, some times github returns an empty hash on the endpoint that returns the statistics (`client.Repositories.ListContributorsStats` on go-github).

I changed `github.go` to debug the issue:

```diff
@@ -415,9 +408,13 @@ func (c *Client) Do(req *http.Request, v interface{}) (*Response, error) {
 		if w, ok := v.(io.Writer); ok {
 			io.Copy(w, resp.Body)
 		} else {
-			err = json.NewDecoder(resp.Body).Decode(v)
+			content, _ := ioutil.ReadAll(response.Body)
+			body2 := ioutil.NopCloser(bytes.NewReader(content))
+			err = json.NewDecoder(body2).Decode(v)
 			if err == io.EOF {
 				err = nil // ignore EOF errors caused by empty response body
+			} else if err != nil {
+				println("Invalid JSON?", string(content))
 			}
 		}
 	}
```

And, it turns out, github returned an empty hash (`{}`) on a repo that wasn't changed the last year...

Is there anything doable on the go-github side? 

FYI: I'm reporting this issue to the GitHub support.

**Comment by caarlos0** [comment]
@shurcooL I just did more tests, seem to be random.

https://github.com/caarlos0/org-stats 

You can exec it against the `docker` org for example.

Not sure it's a bug on github's side anymore.

**Comment by shurcooL** [comment]
Can you reproduce it by hitting their RESP API directly via `curl` or something?

**Comment by caarlos0** [comment]
Reply from github:

```
Hi Carlos,

Thanks for reaching out. An empty has should be valid JSON, and returning that empty hash is indeed expected in that case. The bit that you're missing is that the API is responding with a 202 status in that case, as documented here:

https://developer.github.com/v3/repos/statistics/#a-word-about-caching

When you get back a 202, that means that the statistics haven't been computed yet and you need to make another request to fetch the actual statistics.

I hope this helps!

Best,
Ivan
```

**Comment by caarlos0** [comment]
So, basically, all I had to do is retry when response code is 202... Not sure if it's worth to abstract it in go-github or just leave it as is...

**Comment by shurcooL** [comment]
Ah, yeah, I forgot about that.

I think the best/most appropriate thing for us to do is detect 202 in go-github and return a non-nil error that indicates Accepted status.

As far as I can tell, 202 will always mean "we were not able to return the results you asked for in this call, but we've succesfully scheduled work, so try again later". (Are there any counter-examples?) Returning a non-nil error when the result that was asked for seems very reasonable to me.

Otherwise every use of this library and that function will need to check both `err` and `resp.StatusCode`, which isn't as friendly.

We already detect and return [`RateLimitError`](https://godoc.org/github.com/google/go-github/github#RateLimitError) for rate limit exceeded, etc., which I think is a friendlier API than making the user parse that information out themselves.

**Comment by caarlos0** [comment]
@shurcooL I'm OK with that and I can work on a patch for it tonight. 👍

**Comment by caarlos0** [comment]
@shurcooL done -> https://github.com/google/go-github/pull/488

**Comment by AGMETEOR** [comment]
> Reply from github:
> 
> ```
> Hi Carlos,
> 
> Thanks for reaching out. An empty has should be valid JSON, and returning that empty hash is indeed expected in that case. The bit that you're missing is that the API is responding with a 202 status in that case, as documented here:
> 
> https://developer.github.com/v3/repos/statistics/#a-word-about-caching
> 
> When you get back a 202, that means that the statistics haven't been computed yet and you need to make another request to fetch the actual statistics.
> 
> I hope this helps!
> 
> Best,
> Ivan
> ```

Great explanation
