### ISSUE TITLE
Fix broken integration tests 

### ISSUE THREAD

**Issue by varadarajana** [google/go-github#507]
The integration tests are now broken. 

After cloning the repository, I tried running the integration test cases in the tests/integration folder with GITHUB_AUTH_TOKEN set in environment.

Here is what I did from the GitHub folder
 go get -t -v ./...
 go test -v ../tests/integration/*

Here is the error I got
../tests/integration/repos_test.go:117: branch.Protection undefined (type *github.Branch has no field or method Protection)
...
 ../tests/integration/repos_test.go:140: too many errors
 FAIL command-line-arguments [build failed]

**Comment by varadarajana** [comment]
Here are few changes with which I could fix the issue and wanted to validate the approach before I create a PR and send for review.
The file repos_test.go is broken for EditBranch function. In this function Permissions are not being set with the new APIs. The new API UpdateBranchProtectionRequest requires ProtectionRequest structure. So we need to expose the structure ProtectionRequest from RepositoryServices as integration runs from a different package. Then we can set the values of ProtectionRequest, update Branch and then verify in the same form as done in repos_test.go in GitHub folder. Is this approach fine?

**Comment by shurcooL** [comment]
> So we need to expose the structure ProtectionRequest from RepositoryServices as integration runs from a different package.

I'm not quite sure what you mean by "expose" and "different package". The integration test runs as an external test, so it can only access the public API of the `github` package. That's ideal, because it's what the users would have access to.

At a high level, you want to update the code such that it performs the same functionality as old code, just using the new API that has changed.

If you've already done something, feel free to make a PR so we can take a look at it and make further suggestions. Otherwise, please clarify your question further.

**Comment by varadarajana** [comment]
@shurcooL : can you please review this?
