### ISSUE TITLE
[Question] how to retrieve the all the PR Comments

### ISSUE THREAD

**Issue by ltagliamonte** [google/go-github#525]
Is it possible to retrieve all the comments associated with a PR?
At the moment if I do:
```
searchResults, resp, _ := client.Search.Issues(prSearchPattern, searchOpt)
fmt.Println("The following PRs match the search pattern", prSearchPattern)
for _, pr := range searchResults.Issues {
  		fmt.Println(*pr.Number)
		fmt.Println(*pr.Title)              
		fmt.Println(*pr.Comments)
}
```
pr.Comments is just holding the number of comments associated with the PR.
From the github doc the comments are managed by the Issue Comments API
https://developer.github.com/v3/issues/comments/

**Comment by shurcooL** [comment]
Yes, the endpoint you're looking for is:

[`github.PullRequestsService.ListComments`](https://godoc.org/github.com/google/go-github/github#PullRequestsService.ListComments)

If you want to get absolutely all comments instead of just the first page of comments, then you must take pagination into account. See https://godoc.org/github.com/google/go-github/github#hdr-Pagination.

**Comment by ltagliamonte** [comment]
thank you @shurcooL i opened the issue/question and I then found this https://docs.google.com/spreadsheets/d/1wlHnoJSAN01nXUUF1JobsaKO4mJjAwZNWK8L_4ZSlls/edit?usp=sharing that is really usefull if you like me if new to the library.
