### ISSUE TITLE
Github API for GetRef can return an array, but go-github doesn't handle it.

### ISSUE THREAD

**Issue by samprakos** [google/go-github#588]
https://developer.github.com/v3/git/refs/#get-a-reference

If my ref string matches as a prefix to 1 or more refs, an array is returned.

In this case, I get this error at line 63 of git_refs.go:  json: cannot unmarshal array into Go value of type github.Reference

**Comment by shurcooL** [comment]
Thanks for reporting this. This looks like a valid issue that we need to fix.

Unfortunately, it seems we'd need to change the signature of that endpoint to be able to return multiple refs, since that's what the GitHub API endpoint can sometimes return.

**Comment by aleksclark** [comment]
I'm taking a look at this issue.

**Comment by aleksclark** [comment]
@shurcooL / @gmlewis  just noticing that people generally ask to have issues assigned instead of just submitting PRs, could I be assigned to this?

**Comment by gmlewis** [comment]
Sure, I'll send you an invite which you will need to accept before I can assign you.

**Comment by aleksclark** [comment]
@gmlewis done!

**Comment by aleksclark** [comment]
@shurcooL What if instead of breaking the api, we mark GetRef as deprecated, and add the new code as GetRefs, which would more accurately reflect the nature of the returned value?

**Comment by shurcooL** [comment]
@aleksclark That's actually a pretty great idea. We're lucky that the current naming allows for it.

In fact, I'm thinking perhaps we don't need to deprecate the current method. It depends on how people use them, but I suspect most people only care about a single result, and `GetRef` is easier to work with since it returns a single result rather than a slice containing a single entry. If that's the case, we can keep signature of `GetRef` as is, and people can keep using it if they're happy with at most 1 result.

Then `GetRefs` can be added with ability to return multiple refs.

One thing, I think the current `GetRef` gives an error if GitHub API returns multiple entries, so we should fix that.

From https://developer.github.com/v3/git/refs/#get-a-reference:

> If the `ref` doesn't exist in the repository, but existing refs start with `ref` they will be returned as an array. For example, a call to get the data for a branch named `feature`, which doesn't exist, would return head refs including `featureA` and `featureB` which do.

So, if we're going to keep `GetRef` and not deprecate it, I think the best behavior is to make it return `nil` if there's no exact match (and GitHub API returns multiple similar results).

That way, `GetRef` becomes an exact query. It either returns an exatch match, or nil if it doesn't exist. We need to document that. `GetRefs` becomes a closer mapping to the underlying GitHub API. Users can pick whatever works for their needs better. /cc @gmlewis

How's that sound @aleksclark?

**Comment by aleksclark** [comment]
@shurcooL works for me, I'll take care of it
