### ISSUE TITLE
FYI - Discontinue support for weak cryptographic standards

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#592]
GitHub API Announcement:
https://developer.github.com/changes/2017-03-13-discontinue-support-for-weak-cryptographic-standards/

Note that this should not affect this repo, as we currently support `sha1`, `sha256`, and `sha512` webhook messages in `messages.go`.

This issue is mainly for informational purposes only and can be closed after some short amount of time.

**Comment by bradfitz** [comment]
What does that linked article have to do with the webhook messages we support?

The announcement was about TLS versions (Go is fine) and SSH ciphersuites (unrelated to the go-github package).

One of us is confused. Maybe both. :)

**Comment by shurcooL** [comment]
I'll join in on the confused party.

> What does that linked article have to do with the webhook messages we support?

A _guess_ is that this was meant to be related to [`ValidatePayload`](https://godoc.org/github.com/google/go-github/github#ValidatePayload) func, which internally uses `messageMAC`, which currently does:

```Go
var hashFunc func() hash.Hash
switch sigParts[0] {
case sha1Prefix:
	hashFunc = sha1.New
case sha256Prefix:
	hashFunc = sha256.New
case sha512Prefix:
	hashFunc = sha512.New
default:
	return nil, nil, fmt.Errorf("unknown hash type prefix: %q", sigParts[0])
}
```

Source: https://github.com/google/go-github/blob/839082db564f53df5b8b386f217c7c217b5a624f/github/messages.go#L100-L110.

But I'll let @gmlewis confirm if my guess is right.

**Comment by gmlewis** [comment]
Uh, sorry.  Yes, @shurcooL is right.
I presumed (possibly incorrectly) that GitHub would stop sending their webhook hashes using `sha1` and possibly switch to `sha256` although I didn't read that anywhere.

I was just trying to give an FYI update and let users of this package know that if/when GitHub makes that change, no work needs to be done on this side.

Does that make any sense?

**Comment by reinoudk** [comment]
Hi, I've stumbled upon this issue today as I'm building a service that handles GitHub events. I use the `github.ValidatePayload` function and was surprised that my tests were failing. Turns out I was using the header `X-Hub-Signature-256`, whilst `github.ValidatePayload` has the constant `signatureHeader` defined as `X-Hub-Signature`. 

The GitHub documentation [recommends](https://docs.github.com/en/developers/webhooks-and-events/securing-your-webhooks#validating-payloads-from-github) using `X-Hub-Signature-256`. I've created #1783 that adds support for this header, while keeping the old header as a fallback. 

I hope this is the right issue for that.
