### ISSUE TITLE
The name of `content` in the response of Github Trees API has changed

### ISSUE THREAD

**Issue by kaakaa** [google/go-github#629]
Function [`GetTree`](https://godoc.org/github.com/google/go-github/github#GitService.GetTree) returns the  [Tree](https://godoc.org/github.com/google/go-github/github#Tree) object with empty `content`.
It seems to be caused by the fact that `content` for [Github Trees API](https://developer.github.com/v3/git/trees/#get-a-tree) has changed to the name of `url`.

I'll make PR about changing the name of `Content` in [Tree](https://godoc.org/github.com/google/go-github/github#Tree) to `URL`.

**Comment by shurcooL** [comment]
The [`TreeEntry.Content`](https://godoc.org/github.com/google/go-github/github#TreeEntry.Content) field is not used for [`GetTree`](https://godoc.org/github.com/google/go-github/github#GitService.GetTree), but it is used in [`CreateTree`](https://godoc.org/github.com/google/go-github/github#GitService.CreateTree).

See https://developer.github.com/v3/git/trees/#create-a-tree.

(It's a bit misleading because we reuse the same struct for querying and updating. Perhaps unfortunately so. Changing that would be a breaking API change.)

However, `url` is a new field that was added, so you're welcome to create a PR that adds it. Just don't remove `content`, since it's still valid.

**Comment by kaakaa** [comment]
Thank you for comments! 
As you say, `content` field is needed for CreateTree. I've missed it.
I'll make PR just to add `url` field.
