### ISSUE TITLE
Add topics preview header to more RepositoriesService methods

### ISSUE THREAD

**Issue by bradleyfalzon** [google/go-github#675]
Recently there's been an addition of topics endpoints (in #670 and #672 by @RaviTezu), the GitHub API also responds with a Topics slice in their repository responses such as in https://developer.github.com/v3/repos/#get.

Could we add this to the Repositories type? I'd like the topics response in RepositoriesService.List method.

**Comment by shurcooL** [comment]
> Could we add this to the Repositories type?

Sorry, I don't understand what you're referring to. What would you like added exactly?

Doesn't `Repository` type already have the `Topics` slice? See https://godoc.org/github.com/google/go-github/github#Repository.Topics.

**Comment by bradleyfalzon** [comment]
I must have updated my gopath repo but not my vendored version. My fault. Please ignore!

**Comment by bradleyfalzon** [comment]
OK, my apologies but, I wasn't going crazy, but I did misdiagnose the issue.

I was checking the `RepositoriesService.List` method and that isn't sending the `mediaTypeTopicsPreview` accept header in it's request, which is why I wasn't seeing the correct results.

My apologies for the misdiagnosed issue, but are we able to add this header tot he various `RepositoriesService.List*` methods?

**Comment by RaviTezu** [comment]
@bradleyfalzon  I see it now

We are adding the custom header [mediaTypeTopicsPreview](https://github.com/google/go-github/blob/master/github/github.go#L105) only in `ListAllTopic` and `ReplaceAllTopic` methods. I can take this up, if we decide to include Topics as part of Repository/Repositories returned  in all the List* methods. 

@shurcooL @gmlewis

**Comment by bradleyfalzon** [comment]
Now we know that GitHub will accept multiple accept headers, I'm wondering whether there's another API beyond:

```go
acceptHeaders := []string{mediaTypeLicensesPreview, mediaTypeTopicsPreview, ...}
req.Header.Set("Accept", strings.Join(acceptHeaders, ", "))
```

I was thinking a helper (although a test didn't show a great improvement), but perhaps assigning these accept headers to the service itself, and each method could add just a few more if they need.

**Comment by shurcooL** [comment]
> I was checking the `RepositoriesService.List` method and that isn't sending the `mediaTypeTopicsPreview` accept header in its request, which is why I wasn't seeing the correct results.

@bradleyfalzon I see.

> My apologies for the misdiagnosed issue, but are we able to add this header tot he various `RepositoriesService.List*` methods?

Absolutely.

The [original announcement](https://developer.github.com/changes/2017-07-17-update-topics-on-repositories/) did not mention list endpoints explicitly (/cc @kytrinyx), but I can see in https://developer.github.com/v3/repos/ docs sample responses that topics are indeed a part of some of the list methods too.

So we should add the ones that support this.

Methods to investigate:

- https://godoc.org/github.com/google/go-github/github#RepositoriesService.List
- https://godoc.org/github.com/google/go-github/github#RepositoriesService.ListAll (probably not, but not sure)
- https://godoc.org/github.com/google/go-github/github#RepositoriesService.ListByOrg
- https://godoc.org/github.com/google/go-github/github#RepositoriesService.ListForks
- https://godoc.org/github.com/google/go-github/github#OrganizationsService.ListTeamRepos

Those methods return `[]*github.Repository`. We'll need to confirm which ones do/do not support the topics preview header, and set it only where it's needed.

> I can take this up, if we decide to include Topics as part of Repository/Repositories returned in all the List* methods.

@RaviTezu Feel free to go for it, since this is a supported/documented aspect of GitHub API. Thanks!

Note, this situation is very similar to PR #656.

> perhaps assigning these accept headers to the service itself, and each method could add just a few more if they need.

I'd prefer we don't do that. Let's just keep each method explicit about what headers it sets, and not try to over-set the preview headers. This problem doesn't happen often, and it's easy to fix. We can consider/discuss a more elaborate solution later on, but it doesn't seem to be a net positive to me so far.

In general, we should remember that whenever preview headers are used, it reduces the surface area of the API which `go-github` exposes that can be considered fully stable, reliable, suitable for production use. So it's better to under-set them than over-set.

**Comment by RaviTezu** [comment]
@shurcooL Sure, I will take this up.
@bradleyfalzon @gmlewis

**Comment by kytrinyx** [comment]
> The original announcement did not mention list endpoints explicitly

The change that was made didn't touch the list endpoints explicitly—but that might just mean that the changes were made earlier and weren't announced. I can take a look at this if you're having trouble figuring it out on your end.

**Comment by shurcooL** [comment]
> but that might just mean that the changes were made earlier and weren't announced

When I read that announcement, it certainly felt like it followed another announcement that I had never seen before. Notably:

> Today we're introducing **additions** to the repository topics preview.

After looking through a few pages of posts at https://developer.github.com/changes/, I did not find any other posts related to repository topics preview. I figured I just didn't look hard enough and moved on.

> I can take a look at this if you're having trouble figuring it out on your end.

Thanks @kytrinyx. I think we should be okay, since the sample responses are informative enough. I just mentioned it to give an explanation for why we didn't catch this in the original PR for this feature.

**Comment by kytrinyx** [comment]
> I think we should be okay, since the sample responses are informative enough.

👍 that sounds good. Don't hesitate to ping me, however. :heart:

**Comment by RaviTezu** [comment]
> ❓ https://godoc.org/github.com/google/go-github/github#RepositoriesService.ListAll (probably not, but need to test to confirm)

I just confirmed that, *https://api.github.com/repositories?since=blah* is **not** returning the topics as part of its response. 

Tried with *https://api.github.com/repositories?since=97864963* creating a test repo with topics. BTW the custom header `Accept: application/vnd.github.mercy-preview+json` is set while querying. 
@shurcooL @bradleyfalzon

**Comment by bradleyfalzon** [comment]
> I'd prefer we don't do that. Let's just keep each method explicit about what headers it sets, and not try to over-set the preview headers. 

sgtm.

> In general, we should remember that whenever preview headers are used, it reduces the surface area of the API which go-github exposes that can be considered fully stable, reliable, suitable for production use.

Well said, thanks.
