### ISSUE TITLE
IsTeamMember is Deprecated

### ISSUE THREAD

**Issue by elliott-beach** [google/go-github#717]
The API endpoint backing `OrganizationsService.IsTeamMember` is deprecated in favor of the `GetTeamMembership` endpoint: https://developer.github.com/v3/orgs/teams/#get-team-member.

To discourage API users from unknowingly calling deprecated methods, the documentation for the method should reflect this.

Disagree/Agree?

**Comment by shurcooL** [comment]
Agree. We should deprecate the Go method, explaining reason, and pointing to suggested replacement.

**Comment by e-beach** [comment]
One problem is that it's not easy to use to `GetTeamMembership` check for membership because it returns an error when the member is not part of the team - this is due to a 404 response from the server. But I still think we should maintain the current behavior while deprecating the method.

**Comment by chriskingnet** [comment]
I was looking for a good first contribution to make, and was thinking of picking this up. 

So if I understood correctly, we are looking to maintain the `IsTeamMember` function, but use the `get-team-membership` API call instead? Or was it that we should deprecate the whole Go method and point to using `GetTeamMembership` instead?

Also just as an extra quick point, I noticed that the [https://developer.github.com/v3/orgs/teams/#get-team-membership](get-team-membership) API endpoint is in "preview" mode and subject to change. Not sure if that factors into the decision here, or when would be a good time to work on this. Thanks for your input!

**Comment by gmlewis** [comment]
Thank you for helping out, @chriskingnet!

I think the agreement based on @shurcooL's [comment](https://github.com/google/go-github/issues/717#issuecomment-328364455) was:

- Add a comment to the `OrganizationsService.IsTeamMember` method that it has been deprecated (explaining the reason) and to use the new `GetTeamMembership` method instead (but otherwise, don't modify the method itself).

So this is a documentation change only.
I'll send you an invite so that I can assign the issue to you.

(The "preview" status doesn't typically affect our development of this package. When APIs come out of preview, we remove the special accept header as long as Enterprise customers will not be affected.)

**Comment by chriskingnet** [comment]
OK got it. That's great, thanks a lot!

**Comment by shurcooL** [comment]
This has been resolved by #764, closing.
