### ISSUE TITLE
How to render readme content as HTML?

### ISSUE THREAD

**Issue by Play-Maker** [google/go-github#727]
/* func (s *RepositoriesService) GetReadme(ctx context.Context, owner, repo string, opt *RepositoryContentGetOptions) (*RepositoryContent, *Response, error) */
this func cannot set http header "application/vnd.github.VERSION.html+json".

**Comment by yaoPerfect** [comment]
May be we can add some elements into struct RepositoryContentGetOptions so that we can set http header or body.

**Comment by shurcooL** [comment]
It seems that `RepositoryContentGetOptions` struct is used in many places, I'm not sure if this new struct field would apply to all of them. We should take that into account.

Other than that, adding a struct field makes sense. We've done something similar for #481, that can serve as an example.

**Comment by kshitij10496** [comment]
I would like to give this a try.

**Comment by kshitij10496** [comment]
I would like to share my research on the custom media types supported by the Repo Contents endpoints:

Media Type | Header | Response | Currently Supported
-----|------- | ------ | ------
`html` | `application/vnd.github.v3.html` | Response is raw HTML | No
`raw` | `application/vnd.github.v3.raw` | Response is raw text | No
`object`| `application/vnd.github.v3.object` | This is the default base64 encoded JSON response which we currently support | Yes

**Comment by kshitij10496** [comment]
I have thought of 3 implementations which we can use for supporting different media types for repository contents. I am having a difficulty understanding the which approach is most suitable for our case. Thus, I would like to share them before opening up a PR.

## Set up

Based on the method used in #481 and #767, I created a new type to represent the above-mentioned custom media types as:

```go
type RepositoryContentMediaType uint8

const (
	Object RepositoryContentMediaType = iota // since this is the default
	Raw
	HTML
)
```
---------
### Approach 01: Adding a new parameter to the function signature of `GetReadme` method.

This approach is similar to the one used in #767  where we modified the function signature whereby the user needs to pass in a new argument related to the desired Media Type. Moreover, the signature of these functions is similar to `GetArchiveLink` with the `archiveFormat` type being replaced by the `RepositoryContentMediaType`.

Pros | Cons
-----|------
Separation between API Parameters and Media Types | Not Backwards compatible with current API. Need to implement new methods specific to custom media types.

-----------
### Approach 02: Adding a `MediaType` field to `RepositoryContentGetOptions` struct.

As suggested by @shurcooL above and @willnorris  in #6, I attempted to create a new field to the struct dealing with handling options as:
```go
type RepositoryContentGetOptions struct {
	Ref       string `url:"ref,omitempty"`
	MediaType RepositoryContentMediaType
}
```

However, the problem I am facing here is with the expected behaviour of `addOptions` function used for generating the API endpoint. The function expects the argument passed to it to be a `struct` with "url" tags. Thus, I used an anonymous struct which is then passed onto `addOptions` for processing.

```go
params := struct{
    Ref string `url:"ref,omitempty"`
}{
    opt.Ref
}
```

Pros | Cons
-----|------
Backwards compatible with the current API of various methods (except `GetArchiveLink` method)| We will need to duplicate modification if a new Parameter is added by GitHub to the endpoints.

------------
### Approach 03: Separating the endpoint Parameters from the Media Types

In this approach, I create new types for Parameters(`RepositoryContentParameters`) and Media Types(`RepositoryContentMediaType`). Using these types, I compose the `RepositoryContentGetOptions` as:
```Go
type RepositoryContentGetOptions struct {
    Params    RepositoryContentParameters
    MediaType RepositoryContentMediaType
}
```

Usage example:
```go

// Get README as HTML
client.Repositories.GetReadmeCustom(context.Background(), "owner", "repo",
 &RepositoryContentGetOptions{Params: RepositoryContentParameters{ref: "master"}, 
                              MediaType: HTML})
```

Pros | Cons
-----|------
Design by composition | API becomes too dense and difficult to read
Ease in extending support for future Endpoint Parameters |

**Comment by kshitij10496** [comment]
> I think it'd help us make a decision if we find out how many other places will need support for specifying custom media type.

After reading the GitHub documentation [here](https://developer.github.com/v3/repos/contents/) and grepping through the code, I found the following:
- Methods which should support custom media types for Repository Contents API:
    - `GetReadme`
    - `GetContents` and hence, 
    - `DownloadContents`

- `GetArchiveLink` method is the only place where the `ref` parameter(abstracted by `RepositoryContentGetOptions`) is used but which doesn't support any custom media type.
 
However, if we are discussing support for all the different possible custom media types supported by GitHub API across the entire client, [this](https://developer.github.com/v3/media/) exhaustive list suggests that we don't have to modify many services but there are more than 10 endpoints which support custom mime types. 

I hope this information helps us decide our way forward.

**Comment by kshitij10496** [comment]
@shurcooL Have you had time to think about how should we proceed from here?

Apart from that, I had a suggestion regarding the naming convention of methods for supporting custom media types. 
How about we name them as `GetReadmeCustom` instead of `GetReadmeHTML`? 

Implement a generic method which provides support for media types for each endpoint has 2 advantages:
1. The number of methods we need to implement for supporting mime types for an endpoint is independent of the number of actually supported custom media types. 
2. Extending support for new media types in the future will be easier.

For example, in case of `GetReadme`, a single method `GetReadmeCustom` can support all `HTML`, `raw` and `object` media types.

**Comment by shurcooL** [comment]
@kshitij10496 Sorry, I don't have a lot of bandwidth to dedicate to this issue at this time. See if you can make progress without blocking on me, hopefully other maintainers/contributors can chime in as needed to make progress.

**Comment by wesleimp** [comment]
@gmlewis Can this issue be closed?

**Comment by gmlewis** [comment]
Looking at the history of PRs for this issue, I'm going to close it.
