### ISSUE TITLE
OrganizationsService.ListPendingOrgInvitations does not work

### ISSUE THREAD

**Issue by iwata** [google/go-github#730]
The argument of `ListPendingOrgInvitations` is to pass an integer as `org`, but this is a mistake and I think you should pass the string correctly.

**Comment by shurcooL** [comment]
Thanks for reporting this. You're right.

It's possible to specify an organization via its string name, or via its integer id. However, the endpoint used is "/orgs/:org", which expects the string id. E.g.:

- https://api.github.com/orgs/google - works
- https://api.github.com/orgs/1342004 - doesn't work
- https://api.github.com/organizations/1342004 - works

This was introduced in PR #527. We did not spot the issue there.

We can either change the endpoint to use the intenger-ID based one, or change the signature of the method to take a string instead.

I think it's better to do the latter, since all/most of our methods use string names rather than integer IDs by default (there are a few helpers to use integer IDs, but they're the exception). That way, we maintain better consistency.

Since the function method is not functional, I think a breaking API change is completely okay. No one can be relying on it.

**Comment by shurcooL** [comment]
I've created PR #731 to resolve this issue.
