### ISSUE TITLE
Unit tests should use local client instead of package-global client

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#762]
In https://github.com/google/go-github/pull/732 it became clear that having a package-global `client` for unit testing will prevent the unit tests from being run in parallel in the future.  Ideally, each test will have its own client... something like this:

```go
client, teardown := setup()
defer teardown()
```

and the global `client` in `github_test.go` will be removed.

This would make for a very large PR, but could possibly be done with the assistance of [`gofmt -r`](https://blog.golang.org/go-fmt-your-code) or your favorite text editor. :smile: 

This would also be a great project for a new contributor to the repo. Let it be known that all help is greatly appreciated! Thank you in advance.

**Comment by chriskingnet** [comment]
I decided to have a go at this issue, sorry I forgot to comment here first. This was quite a nice one to do as a new contributor :)

**Comment by shurcooL** [comment]
@gmlewis I don't think it'll be sufficient to have `setup` return only `client`. I think it'll need to return `server` and `mux` as well. Otherwise, it's not sufficient to achieve the goal of avoiding global shared state between tests.

**Comment by chriskingnet** [comment]
Makes sense, thanks for input @shurcooL. From a quick check, there does actually seem to be a couple of tests using the global `server` in order to get its URL. 

So in order to not change any of the tests, we would have setup() always return the four things (I like explicitly returning teardown rather than just having every test call server.Close):

```go
client, mux, server, teardown := setup()
```

Or we could do something like (naming tbc):

```go
client, mux, globalConfig, teardown := setup()
```
where global config contains configuration details that might be needed in tests - i.e. the server base URL value. 

Any thoughts?

**Comment by shurcooL** [comment]
How about this:

```Go
server, mux, client := setup()
defer server.Close()
```

Since everything that `teardown` does fits on one line, I think we can just get rid of it.

**Comment by chriskingnet** [comment]
That's true. Although I quite liked that it is explicit, and that to "forget" to teardown I have to purposefully ignore the variable and use `_`, otherwise I will get an error for not using it. If we rely on calling server.Close(), I think that this step might be more easily missed.

That said, I imagine almost all tests written will just copy a previous one, which will have the code you mentioned in it. So in practice I'm not sure how much of a problem that is.

**Comment by chriskingnet** [comment]
Ah, sorry, I replied before I saw your updated comment!

>Is the server base URL value the only thing used by tests? If so, maybe just return that url instead of globalConfig?

Yes, that sound like a good approach. So we're now at:

```go
serverBaseURL, mux, client, teardown := setup()
defer teardown()
```

...giving the tests what they need and not over complicating when we only need that one value at the moment.
