### ISSUE TITLE
github-accessors.go: Missing accessors for non-Struct type fields

### ISSUE THREAD

**Issue by sahildua2305** [google/go-github#775]
While working on #770, I noticed that we are creating accessors only for fields which have a struct type. I looked further into it today and confirmed the same. Is this intentional? If so, why?
/cc @gmlewis @shurcooL

**Comment by gmlewis** [comment]
I'm not sure I understand what you mean.
https://github.com/google/go-github/blob/master/github/github-accessors.go#L24
returns a `string`, for example.

**Comment by shurcooL** [comment]
@sahildua2305 Can you give some examples of fields that are missing accessors?

**Comment by sahildua2305** [comment]
For example - https://github.com/google/go-github/blob/8c08f4fba5e05e0fd2821a5f80cf0cf643bd5314/github/activity.go#L30
here - `CurrentUserOrganizationURLs` won't have any accessor because of the following logic -
https://github.com/google/go-github/blob/8c08f4fba5e05e0fd2821a5f80cf0cf643bd5314/github/gen-accessors.go#L103

**Comment by shurcooL** [comment]
The type of that particular field `CurrentUserOrganizationURLs` is `[]string`. It’s not a pointer.

Not having an accessor for it seems reasonable, since the accessors exist for pointer fields to help prevent `nil` pointer dereference panics when a field is missing. Since there’s no pointer here, there’s nothing to protect against. Does that make sense? Or am I missing something? What would having an accessor for that field accomplish?

**Comment by sahildua2305** [comment]
Oh right! Makes sense. I knew I might be missing something. Thanks for clearing it out. 💯
