### ISSUE TITLE
Adding a simple working program under the Usage section of the README

### ISSUE THREAD

**Issue by kshitij10496** [google/go-github#809]
Hello,

I am writing a simple Go program which uses this package to make some API calls to GitHub as part of learning Go. It took me some redirections to get started with the package to make native Unauthenticated and Basic authenticated calls; probably due to my naivety at reading/writing Go code.

Hence, I thought of mentioning this so as to help beginners (like me) pick the package up quicker in the future. I would like to suggest having at least one complete working code snippet which can be used exclusively as a copy-paste program. This can be achieved in two ways:
1. Adding a link to the `examples` directory in the "Usage" section.
2. Modify the already present examples to be inclusive enough for direct use as recipes.

Since I am totally new to Go development environment, I beg pardon if my suggestions seem rather ingenuous to the more experienced community members.

**Comment by shurcooL** [comment]
Hi there, thank you for feedback and suggestions, they are appreciated.

I agree this is important, especially because `go-github` is a good first package to play with for people who just installed Go.

We do need to be careful to strike the right balance of providing the right amount of information in the README and package documentation (i.e., https://godoc.org/github.com/google/go-github/github), so that it's helpful and easy to scan for most people trying to look something up, as well as contain enough information for beginners to be able to get started.

I've looked at PR #810 and I think it's a good start. I have some feedback on how we can make it better, I'll post it there.

**Comment by sahildua2305** [comment]
@kshitij10496 thanks for the feedback and #810. Highly appreciated.

**Comment by kshitij10496** [comment]
Thank you guys for the appreciation.
It would be my pleasure to learn Go while contributing to this package.

Since all the issues tagged "good first issue" are currently under development and the endpoints mentioned in the [roadmap](https://docs.google.com/spreadsheets/d/1wlHnoJSAN01nXUUF1JobsaKO4mJjAwZNWK8L_4ZSlls/edit#gid=0) have all been implemented(needs update), I would appreciate if you can point me to other beginner-friendly ways I can contribute to this package.

**Comment by shurcooL** [comment]
> Since all the issues tagged "good first issue" are currently under development

Is that really the case? I'd suggest double checking if you haven't already. If an issue was started but there's been no progress for over a week, it's completely okay to ping and inquire on the status. Sometimes issues are started but then get stuck, so you might be able to resume one of the existing ones and help push it along.

Otherwise, it means there's not much to do, which isn't a bad thing. :) Just watch this repository and when a new issue comes up, see if it's something you'd want to try to tackle. Thanks again!

**Comment by FenwickElliott** [comment]
Hi,

I too am very new to Go but in investigating this repo I wrote up what I think you're talking about.

I never intended if for anyone else so it's rough and undocumented but if it's helpful I'd be happy to polish it up for you or anyone else:

https://github.com/FenwickElliott/GoGit/blob/master/main.go

wrt: the token, I simply saved it as a string in txt file called 'token' in the same directory. I have another script for gettin OAuth2 access through a browser if you'd like that too.
