### ISSUE TITLE
Starring an issue returns 404

### ISSUE THREAD

**Issue by ribice** [google/go-github#815]
I'm trying to invoke client.Activity.Star(context, author, project) while being logged in and I'm constantly getting 404s.

PUT https://api.github.com/user/starred/fatih/color: 404 Not Found []&{0xc4201fc0a0 <nil>}

The URL and implementation seem valid.

[GIST](https://gist.github.com/ribice/de1a7d419efefb75d03906d3af1c5590) (replace ghKey with your own)

**Comment by ribice** [comment]
[GIST](https://gist.github.com/ribice/de1a7d419efefb75d03906d3af1c5590)

**Comment by kshitij10496** [comment]
Hey @ribice 

The issue seems to be with the scope of the authentication token you are providing rather than with this library. GitHub returns 404 for the requests because the scope of your access token is not sufficient provides and the scope needed for starring a repository.
From personal experimentation, I found that defining "repo" access will make this work.

Refer: [Authentication](https://developer.github.com/v3/#authentication)

**Comment by ribice** [comment]
Thanks @kshitij10496. That was it. Although I did not expect to get 404 for this.
