### ISSUE TITLE
No way to inspect the body after receiving a 202

### ISSUE THREAD

**Issue by SamWhited** [google/go-github#862]
When a 202 is returned, an `AcceptedError` is returned by `client.Do` and the `resp.Body` is closed. The body is never read or decoded into the result parameter, so there is no way to inspect the body. However, I am beta testing an experimental endpoint that returns URLs you need to check the status of your request so I need access to the body.

I am not sure if any existing endpoints return a body in 202s, but some will in the future so it would be nice if we could access the body.

**Comment by shurcooL** [comment]
> I am beta testing an experimental endpoint that returns URLs

Can you clarify what you mean? Is it an experimental GitHub REST API v3 endpoint?

If/when GitHub does add an endpoint that returns meaningful data with 202 status code, then we can make changes to support reading the body. I don't think we should do it before that.

We would need to know the schema/encoding of the body to be able to parse it, otherwise the best go-github could do is return it as a byte slice. But that's not very friendly.

**Comment by shurcooL** [comment]
> I went and looked, some of their existing APIs do too. For example: https://developer.github.com/v3/repos/#transfer-a-repository

Thanks, that’s helpful.

I agree, we should support that endpoint returning the repository data when response status code is 202.

**Comment by chughpiyush** [comment]
@gmlewis This too can be closed as the PR is already merged.

**Comment by gmlewis** [comment]
Closing as fixed by #878.
