### ISSUE TITLE
Add Issue/PR template in CommunityHealthFiles

### ISSUE THREAD

**Issue by joan-saum** [google/go-github#956]
Thanks to this endpoint : https://developer.github.com/v3/repos/community/

We can get some interesting datas.
Type CommunityHealthFiles contain CodeOfConduct, Contributing, License and Readme files, but not issue template and pull requests files. It might be a good idea to include them into CommunityHealthFiles

**Comment by gmlewis** [comment]
Thank you, @joan-saum!

Yes, specifically, we could add support for these fields:

```json
    "issue_template": {
      "url": "https://api.github.com/repos/octocat/Hello-World/contents/ISSUE_TEMPLATE",
      "html_url": "https://github.com/octocat/Hello-World/blob/master/ISSUE_TEMPLATE"
    },
    "pull_request_template": {
      "url": "https://api.github.com/repos/octocat/Hello-World/contents/PULL_REQUEST_TEMPLATE",
      "html_url": "https://github.com/octocat/Hello-World/blob/master/PULL_REQUEST_TEMPLATE"
    },
```

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept after you enable two-factor authentication) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by gmlewis** [comment]
I'm thinking that we could simply reuse the `Metric` struct in both cases in the file `repos_community_health.go` and the `Name` and `Key` fields would simply not be populated.

**Comment by joan-saum** [comment]
I'm volunteer to handle this issue
I thought the same, simply reuse the `Metric` struct. It will better way to have a clean and common code.
