### ISSUE TITLE
Should UpdateCheckRunOptions.Name be a pointer to a string?

### ISSUE THREAD

**Issue by gauntface** [google/go-github#976]
Just working on some changes and I wasn't sure if the Name field should be a string or pointer to a string:

https://github.com/google/go-github/blob/b93adc1c7febaf7dad1bed965e5310a86bc2623e/github/checks.go#L168-L170

**Comment by gmlewis** [comment]
When I try to figure out the answer to this question, I first look at the GitHub Developer API docs and see if it is a required field.

In this case, although the docs don't say that `name` is required, it doesn't say 'optional' either and it seems like all calls should have the `name` field.

If the parameter is always passed and there are no circumstances where we don't want it to be passed, we don't need to make it a pointer.

The problem comes if we don't want to set a parameter when talking to the server (in a request) or the server sometimes doesn't populate the field (in a response). In those cases, we make the field a pointer and add the json tag `omitempty` so that when sending the request, that field will not even show up in the json request.

This situation is particularly glaring and (easier to understand) for `bool`s. When sending a `bool` field in a request, if we didn't make it a pointer and didn't use `omitempty`, then the `bool` would be sent with the value `false`, whereas if we make it a pointer and use `omitempty`, the field will not be sent at all.

So in this case, I think it is fine to leave as a non-pointer `string`.

I hope that makes sense. Please let me know if you have any other questions.

**Comment by gauntface** [comment]
Totally makes sense, I just wanted to make sure. I had a hunch that it was because it was required, but still new to the lib and hadn't seen it anywhere else.

Thanks for the helpful response.
